Bug 1356: Intermediate merge with the trunk.

diff --git a/branches/CEP-Calibration-Bug1356-task-branch/CEP/Calibration/BBSControl/src/calibrate b/branches/CEP-Calibration-Bug1356-task-branch/CEP/Calibration/BBSControl/src/calibrate
--- a/branches/CEP-Calibration-Bug1356-task-branch/CEP/Calibration/BBSControl/src/calibrate
+++ b/branches/CEP-Calibration-Bug1356-task-branch/CEP/Calibration/BBSControl/src/calibrate
@@ -3,22 +3,22 @@
 # calibrate: top-level calibration script.
 #
 # Copyright (C) 2009
-# ASTRON (Netherlands Foundation for Research in Astronomy)
-# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
+# ASTRON (Netherlands Institute for Radio Astronomy)
+# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
 #
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# This file is part of the LOFAR software suite.
+# The LOFAR software suite is free software: you can redistribute it and/or
+# modify it under the terms of the GNU General Public License as published
+# by the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
-# This program is distributed in the hope that it will be useful,
+# The LOFAR software suite is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
-# You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
+# You should have received a copy of the GNU General Public License along
+# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
 #
 # $Id$
 
@@ -44,9 +44,10 @@ usage()
     echo "options:"
     echo "  -h, --help        display this help text"
     echo "  -v, --verbose     be verbose"
-    echo "  -f, --force       clean control database, sky model parmdb, and"
-    echo "                    instrument model parmdb"
+    echo "  -f, --force       expands to --clean, --replace-sky-db,"
+    echo "                    --replace-instrument-db"
     echo "  --dry             do not start any processes"
+    echo "  --clean           clean control database for the specified key"
     echo "  --key keyname     unique key to identify the session"
     echo "                    (default: default)"
     echo "  --cluster-desc    cluster description file"
@@ -57,30 +58,38 @@ usage()
     echo "  --db-user user    name of the control db user (default: ${USER})"
     echo "  --port-range      range of ports to try when starting global solver"
     echo "      low:high      (default: 6500 through 6599)"
-    echo "  --instrument-db   path to a non-default instrument model parmdb"
-    echo "  --instrument-name basename for the instrument model pparmdb"
-    echo "                    (default: instrument)"
-    echo "  --sky-name        basename for the sky model parmdb"
+    echo "  --skip-sky-db     skip setup of a distributed sky model parmdb"
+    echo "  --replace-sky-db  replace existing sky model parmdb"
+    echo "  --sky-db          path to a non-default sky model parmdb"
+    echo "  --sky-basename    basename for the sky model parmdb"
     echo "                    (default: sky)"
-    echo "  --no-setup        do not setup an instrument and sky model parmdb"
+    echo "  --skip-instrument-db"
+    echo "                    skip setup of a distributed instrument model"
+    echo "                    parmdb"
+    echo "  --replace-instrument-db"
+    echo "                    replace existing instrument model parmdb"
+    echo "  --instrument-db   path to a non-default instrument model parmdb"
+    echo "  --instrument-basename"
+    echo "                    basename for the instrument model parmdb"
+    echo "                    (default: instrument)"
     exit 1
 }
 
 error()
 {
-    echo "\033[1;31m"`date` "[FAIL] error: $1\033[m"
+    echo "\033[1;31m"`date` "[FAIL] error: ${1}\033[m"
     exit 1
 }
 
 event()
 {
-    echo "\033[1;32m`date` $1\033[m"
+    echo "\033[1;32m`date` ${1}\033[m"
 }
 
 kill_all()
 {
-    event "kill local process(es): $1"
-    for pid in $1; do
+    event "kill local process(es): ${1}"
+    for pid in ${1}; do
         kill -9 "${pid}" >/dev/null 2>&1
     done
 }
@@ -94,7 +103,7 @@ echo "calibrate (top-level calibration script) "`date`
 echo
 
 # Find the path used to start the script.
-pgmpath=`dirname $0`
+pgmpath=`dirname ${0}`
 pgmpath=`cd ${pgmpath} > /dev/null 2>&1  &&  pwd`
 
 # Get LOFARROOT.
@@ -105,21 +114,26 @@ fi
 # Options
 help=0
 verbose=0
-solver=0
-port_low=6500
-port_high=6599
+force=0
+dry=0
+clean=0
+key="default"
+cluster_desc="${HOME}/CEP.clusterdesc"
 db_host="localhost"
 db_port=5432
 db_name=${USER}
 db_user=${USER}
-key="default"
-force=0
-dry=0
-cluster_desc="${HOME}/CEP.clusterdesc"
+solver=0
+port_low=6500
+port_high=6599
+skip_sky_db=0
+replace_sky_db=0
+sky_db=
+sky_basename="sky"
+skip_instrument_db=0
+replace_instrument_db=0
 instrument_db=
-instrument_name="instrument"
-sky_name="sky"
-setup=1
+instrument_basename="instrument"
 
 # Arguments
 observation=
@@ -130,104 +144,124 @@ wd=
 # Parse command line.
 while test $# -ne 0
 do
-  if test "$1" = "-h" -o "$1" = "--help"; then
+  if test "${1}" = "-h" -o "${1}" = "--help"; then
     help=1
     break
-  elif test "$1" = "-v"  -o  "$1" = "--verbose"; then
+  elif test "${1}" = "-v"  -o  "${1}" = "--verbose"; then
     shift
     verbose=1
-  elif test "$1" = "-f" -o "$1" = "--force"; then
+  elif test "${1}" = "-f" -o "${1}" = "--force"; then
     shift
     force=1
-  elif test "$1" = "--dry"; then
+  elif test "${1}" = "--dry"; then
     shift
     dry=1
-  elif test "$1" = "--no-setup"; then
+  elif test "${1}" = "--clean"; then
     shift
-    setup=0
-  elif test "$1" = "--key"; then
+    clean=1
+  elif test "${1}" = "--skip-sky-db"; then
+    shift
+    skip_sky_db=1
+  elif test "${1}" = "--replace-sky-db"; then
+    shift
+    replace_sky_db=1
+  elif test "${1}" = "--skip-instrument-db"; then
+    shift
+    skip_instrument_db=1
+  elif test "${1}" = "--replace-instrument-db"; then
+    shift
+    replace_instrument_db=1
+  elif test "${1}" = "--key"; then
     if test $# -le 1; then
-        error "$1 needs an additional argument"
+        error "${1} needs an additional argument"
     fi
     shift
 
-    key=$1
+    key=${1}
     shift
-  elif test "$1" = "--db"; then
+  elif test "${1}" = "--db"; then
     if test $# -le 1; then
-        error "$1 needs an additional argument"
+        error "${1} needs an additional argument"
     fi
     shift
 
     # Parse hostname:port string.
     tmp=${1%%:*}
     db_host=${tmp:-$db_host}
-    if test "${1##*:}" != "$1"; then
+    if test "${1##*:}" != "${1}"; then
         tmp=${1##*:}
         db_port=${tmp:-$db_port}
     fi
     shift
-  elif test "$1" = "--db-name"; then
+  elif test "${1}" = "--db-name"; then
     if test $# -le 1; then
-        error "$1 needs an additional argument"
+        error "${1} needs an additional argument"
     fi
     shift
 
-    db_name=$1
+    db_name=${1}
     shift
-  elif test "$1" = "--db-user"; then
+  elif test "${1}" = "--db-user"; then
     if test $# -le 1; then
-        error "$1 needs an additional argument"
+        error "${1} needs an additional argument"
     fi
     shift
 
-    db_user=$1
+    db_user=${1}
     shift
-  elif test "$1" = "--instrument-db"; then
+  elif test "${1}" = "--sky-db"; then
     if test $# -le 1; then
-        error "$1 needs an additional argument"
+        error "${1} needs an additional argument"
     fi
     shift
 
-    instrument_db=$1
+    sky_db=${1}
     shift
-  elif test "$1" = "--instrument-name"; then
+  elif test "${1}" = "--sky-name"; then
     if test $# -le 1; then
-        error "$1 needs an additional argument"
+        error "${1} needs an additional argument"
     fi
     shift
 
-    instrument_name=$1
+    sky_basename=${1}
     shift
-  elif test "$1" = "--sky-name"; then
+  elif test "${1}" = "--instrument-db"; then
     if test $# -le 1; then
-        error "$1 needs an additional argument"
+        error "${1} needs an additional argument"
     fi
     shift
 
-    sky_name=$1
+    instrument_db=${1}
     shift
-  elif test "$1" = "--port-range"; then
+  elif test "${1}" = "--instrument-name"; then
     if test $# -le 1; then
-        error "$1 needs an additional argument"
+        error "${1} needs an additional argument"
+    fi
+    shift
+
+    instrument_basename=${1}
+    shift
+  elif test "${1}" = "--port-range"; then
+    if test $# -le 1; then
+        error "${1} needs an additional argument"
     fi
     shift
 
     # Parse low:high string.
     tmp=${1%%:*}
     port_low=${tmp:-$port_low}
-    if test "${1##*:}" != "$1"; then
+    if test "${1##*:}" != "${1}"; then
         tmp=${1##*:}
         port_high=${tmp:-$port_high}
     fi
     shift
-  elif test "$1" = "--cluster-desc"; then
+  elif test "${1}" = "--cluster-desc"; then
     if test $# -le 1; then
-        error "$1 needs an additional argument"
+        error "${1} needs an additional argument"
     fi
     shift
 
-    cluster_desc=$1
+    cluster_desc=${1}
     shift
   else
     break
@@ -239,10 +273,10 @@ if test $# -ne 4 -o ${help} -eq 1; then
 fi
 
 # Get arguments.
-observation=$1
-parset=$2
-catalogue=$3
-wd=$4
+observation=${1}
+parset=${2}
+catalogue=${3}
+wd=${4}
 
 # Get absolute paths.
 tmp=`dirname ${observation}`
@@ -266,6 +300,10 @@ echo "    wd: ${wd}"
 echo
 
 if test ${verbose} -eq 1; then
+    echo "    verbose: ${verbose}"
+    echo "    force: ${force}"
+    echo "    dry: ${dry}"
+    echo "    clean: ${clean}"
     echo "    key: ${key}"
     echo "    cluster_desc: ${cluster_desc}"
     echo "    db: ${db_host}:${db_port}"
@@ -273,13 +311,14 @@ if test ${verbose} -eq 1; then
     echo "    db user: ${db_user}"
     echo "    solver: ${solver}"
     echo "    port range: ${port_low}:${port_high}"
+    echo "    skip sky db: ${skip_sky_db}"
+    echo "    replace sky db: ${replace_sky_db}"
+    echo "    sky db: ${sky_db}"
+    echo "    sky name: ${sky_basename}"
+    echo "    skip instrument db: ${skip_instrument_db}"
+    echo "    replace instrument db: ${replace_instrument_db}"
     echo "    instrument db: ${instrument_db}"
-    echo "    instrument name: ${instrument_name}"
-    echo "    sky name: ${sky_name}"
-    echo "    setup: ${setup}"
-    echo "    force: ${force}"
-    echo "    dry: ${dry}"
-    echo "    verbose: ${verbose}"
+    echo "    instrument name: ${instrument_basename}"
     echo
 fi
 
@@ -300,6 +339,10 @@ if test ! -r "${cluster_desc}"; then
     error "unreadable file: ${cluster_desc}"
 fi
 
+if test "${sky_db}" -a ! -d "${sky_db}"; then
+    error "not a directory: ${sky_db}"
+fi
+
 if test "${instrument_db}" -a ! -d "${instrument_db}"; then
     error "not a directory: ${instrument_db}"
 fi
@@ -317,12 +360,18 @@ echo
 # Parse boolean from parset.
 if test "${parset_solver}" = "T" -o "${parset_solver}" = "t" -o "${parset_solver}" = "Y" -o "${parset_solver}" = "y" -o "${parset_solver}" = "1"; then
     solver=1
-fi    
+fi
+
+if test ${force} -eq 1; then
+    clean=1
+    replace_sky_db=1
+    replace_instrument_db=1
+fi
 
 # CLEAN DATABASE
 #
 
-if test ${force} -eq 1; then
+if test ${clean} -eq 1; then
     event "clean database for key ${key}"
 
     if test ${dry} -eq 0; then
@@ -342,35 +391,61 @@ fi
 # SETUP PARAMETER DATABASES
 #
 
-if test ${setup} -eq 1; then
-  overwrite="-nooverwrite"
-  if test ${force} -eq 1; then
-      overwrite="-overwrite"
-  fi
 
-  event "execute setupsourcedb"
-  if test ${verbose} -eq 1 -o ${dry} -eq 1; then
-      echo "setupsourcedb \"${overwrite}\" \"${observation}\" \"${catalogue}\" \"${sky_name}\" \"${cluster_desc}\" \"${key}_setupsourcedb-part_$$.log\" nodry"
-  fi
+if test ${skip_sky_db} -eq 0; then
+    event "make distributed sky model parmdb"
 
-  if test ${dry} -eq 0; then
-      setupsourcedb "${overwrite}" "${observation}" "${catalogue}" "${sky_name}" "${cluster_desc}" "${key}_setupsourcedb-part_$$.log" nodry
-      if test $? -ne 0; then
-          error "setupsourcedb or remote setupsourcedb-part process(es) failed"
-      fi
-  fi
+    overwrite="-nooverwrite"
+    if test ${replace_sky_db} -eq 1; then
+        overwrite="-overwrite"
+    fi
 
-  event "execute setupparmdb"
-  if test ${verbose} -eq 1 -o ${dry} -eq 1; then
-      echo "setupparmdb \"${overwrite}\" \"${observation}\" \"${instrument_db}\" \"${instrument_name}\" \"${cluster_desc}\" \"${key}_setupparmdb-part_$$.log\" nodry"
-  fi
+    if test "${sky_db}"; then
+        event "execute setupparmdb"
+        if test ${verbose} -eq 1 -o ${dry} -eq 1; then
+            echo "setupparmdb \"${overwrite}\" \"${observation}\" \"${sky_db}\" \"${sky_basename}\" \"${cluster_desc}\" \"${key}_skip_sky_parmdb_$$.log\" nodry"
+        fi
 
-  if test ${dry} -eq 0; then
-      setupparmdb "${overwrite}" "${observation}" "${instrument_db}" "${instrument_name}" "${cluster_desc}" "${key}_setupparmdb-part_$$.log" nodry
-      if test $? -ne 0; then
-          error "setupparmdb or remote setupparmdb-part process(es) failed"
-      fi
-  fi
+        if test ${dry} -eq 0; then
+          setupparmdb "${overwrite}" "${observation}" "${sky_db}" "${sky_basename}" "${cluster_desc}" "${key}_skip_sky_parmdb_$$.log" nodry
+          if test $? -ne 0; then
+              error "setupparmdb or remote setupparmdb-part process(es) failed"
+          fi
+        fi
+    else
+        event "execute setupsourcedb"
+        if test ${verbose} -eq 1 -o ${dry} -eq 1; then
+            echo "setupsourcedb \"${overwrite}\" -makeopt 'format=<' \"${observation}\" \"${catalogue}\" \"${sky_basename}\" \"${cluster_desc}\" \"${key}_skip_sky_parmdb_$$.log\" nodry"
+        fi
+
+        if test ${dry} -eq 0; then
+            setupsourcedb "${overwrite}" -makeopt 'format=<' "${observation}" "${catalogue}" "${sky_basename}" "${cluster_desc}" "${key}_skip_sky_parmdb_$$.log" nodry
+            if test $? -ne 0; then
+                error "setupsourcedb or remote setupsourcedb-part process(es) failed"
+            fi
+        fi
+    fi
+fi
+
+if test ${skip_instrument_db} -eq 0; then
+    event "make distributed instrument model parmdb"
+
+    overwrite="-nooverwrite"
+    if test ${replace_instrument_db} -eq 1; then
+        overwrite="-overwrite"
+    fi
+
+    event "execute setupparmdb"
+    if test ${verbose} -eq 1 -o ${dry} -eq 1; then
+        echo "setupparmdb \"${overwrite}\" \"${observation}\" \"${instrument_db}\" \"${instrument_basename}\" \"${cluster_desc}\" \"${key}_skip_instrument_db_$$.log\" nodry"
+    fi
+
+    if test ${dry} -eq 0; then
+        setupparmdb "${overwrite}" "${observation}" "${instrument_db}" "${instrument_basename}" "${cluster_desc}" "${key}_skip_instrument_db_$$.log" nodry
+        if test $? -ne 0; then
+            error "setupparmdb or remote setupparmdb-part process(es) failed"
+        fi
+    fi
 fi
 
 #
@@ -416,7 +491,7 @@ event "execute GlobalControl"
 if test ${verbose} -eq 1 -o ${dry} -eq 1; then
     echo "GlobalControl ${key}_control_$$.parset 0"
 fi
-    
+
 if test ${dry} -eq 0; then
     GlobalControl "${key}_control_$$.parset" 0 > "${key}_control_$$.log" 2>&1 &
     pidlist="${pidlist} $!"
@@ -424,7 +499,7 @@ fi
 
 if test ${solver} -eq 1; then
     event "execute SolverControl"
-    
+
     if test ${verbose} -eq 1 -o ${dry} -eq 1; then
         echo "SolverControl ${key}_solver_$$.parset 0"
     fi
@@ -452,11 +527,11 @@ fi
 
 event "execute remote KernelControl processes"
 if test ${verbose} -eq 1 -o ${dry} -eq 1; then
-    echo "startdistproc -mode 0 -nomasterhost -dsn \"${observation}\" -cdn \"${cluster_desc}\" -logfile \"${key}_calibrate-part_$$.log\" \"${pgmpath}/calibrate-part\" \"${LOFARROOT}\" \"${wd}\" \"${key}\" \"${db_host}\" \"${db_port}\" \"${db_name}\" \"${db_user}\" \"${instrument_name}\" \"${sky_name}\" nodry"
-fi    
+    echo "startdistproc -useenv -mode 0 -nomasterhost -dsn \"${observation}\" -cdn \"${cluster_desc}\" -logfile \"${key}_calibrate-part_$$.log\" \"${pgmpath}/calibrate-part\" \"${LOFARROOT}\" \"${wd}\" \"${key}\" \"${db_host}\" \"${db_port}\" \"${db_name}\" \"${db_user}\" \"${instrument_basename}\" \"${sky_basename}\" nodry"
+fi
 
 if test ${dry} -eq 0; then
-    startdistproc -mode 0 -nomasterhost -dsn "${observation}" -cdn "${cluster_desc}" -logfile "${key}_calibrate-part_$$.log" "${pgmpath}/calibrate-part" "${LOFARROOT}" "${wd}" "${key}" "${db_host}" "${db_port}" "${db_name}" "${db_user}" "${instrument_name}" "${sky_name}" nodry
+    startdistproc -useenv -mode 0 -nomasterhost -dsn "${observation}" -cdn "${cluster_desc}" -logfile "${key}_calibrate-part_$$.log" "${pgmpath}/calibrate-part" "${LOFARROOT}" "${wd}" "${key}" "${db_host}" "${db_port}" "${db_name}" "${db_user}" "${instrument_basename}" "${sky_basename}" nodry
 
     if test $? -ne 0; then
         kill_all "${pidlist}"
@@ -464,7 +539,7 @@ if test ${dry} -eq 0; then
     fi
 fi
 
-    
+
 #
 # SHUTDOWN
 #
