BugID: 962 Added support for Cray XT3 by testing on yod/qsub

diff --git a/trunk/autoconf_share/assay b/trunk/autoconf_share/assay
--- a/trunk/autoconf_share/assay
+++ b/trunk/autoconf_share/assay
@@ -142,14 +142,27 @@
   NEEDOUTFIL=$1
   shift
 
-# Use LimitExec if available
+# If running on a Cray cluster, we have to use qsub and yod.
+# If found, the result is a path, thus starts with a slash.
+  LOFAR_USECRAY=1
+  QSUBP=`which qsub 2>&1 | sed -e 's%^[^/].*%%'`
+  YODP=`which yod 2>&1 | sed -e 's%^[^/].*%%'`
+  if [ "$QSUBP" = ""  -o  "$YODP" = "" ]
+  then
+    LOFAR_USECRAY=0         # No Cray
+  fi
+  export LOFAR_USECRAY
+
+# Use LimitExec if possible and available.
   LOFAR_LIMITEXEC=
-  if [ -x $LOFARROOT/bin/LimitExec ]
-  then
-    LOFAR_LIMITEXEC="$LOFARROOT/bin/LimitExec"
-  elif [ -x $lofar_sharedir/limitexec.sh ]
-  then
-    LOFAR_LIMITEXEC="$lofar_sharedir/limitexec.sh"
+  if [ LOFAR_USECRAY = 0 ]; then
+    if [ -x $LOFARROOT/bin/LimitExec ]
+    then
+      LOFAR_LIMITEXEC="$LOFARROOT/bin/LimitExec"
+    elif [ -x $lofar_sharedir/limitexec.sh ]
+    then
+      LOFAR_LIMITEXEC="$lofar_sharedir/limitexec.sh"
+    fi
   fi
   export LOFAR_LIMITEXEC
   if [ "$LOFAR_LIMITEXEC" != "" ]
@@ -182,51 +195,92 @@
   fi
 
 
-
 # Define exit and interrupt handler.
   trap 'rm -rf core ${PROG}_tmp* ; \
         trap - 0 ; \
         exit $STATUS' 0 1 2 3 15
 
-# If there is a .run file then use it.
+# If there is a .run file then use it (not on the Cray).
   if [ -f "$PROG.run" ]
   then
-     COMMAND="./$PROG.run"
-     LOFAR_CHECKTOOL="$CHKTOOL"
-     export LOFAR_CHECKTOOL
+    if [ $LOFAR_USECRAY = 1 ]; then
+      echo "UNTESTED (no .run support): $*"
+      exit 3
+    fi
+    COMMAND="./$PROG.run"
+    LOFAR_CHECKTOOL="$CHKTOOL"
+    export LOFAR_CHECKTOOL
   fi
 
 # Execute the command.
-  eval "$COMMAND" > ${PROG}_tmp.out
-  STATUS=$?
+  if [ $LOFAR_USECRAY = 1 ]; then
+    # On the Cray create a batch job which will use a single processor.
+    # Copy the AIPSPATH definition (if defined).
+    # Because the job does not wait, we do that by using a wait file.
+    # Note that yod does wait.
+    if test "$AIPSPATH" != ""; then
+      $PBS_AIPSPATH="PBS -v $AIPSPATH"
+    fi
+    rm -f ${PROG}_tmp.wait
+    cat > ${PROG}_tmp.qsub <<EOF
+#PBS -l size=1
+#PBS -N ${PROG}_tmp_job
+#PBS -j oe
+#$PBS_AIPSPATH
+cd \$PBS_O_WORKDIR
+yod -sz 1 ./$PROG > ${PROG}_tmp.out
+touch ${PROG}_tmp.wait
+EOF
+    # Submit the job and wait for it to be finished.
+    # Do not wait longer than 10 minutes.
+    qsub ${PROG}_tmp.qsub
+    NRTIMES=0
+    while [ ! -f ${PROG}_tmp.wait ]
+    do
+      if test $NRTIMES -gt 600
+      then
+        # Keep job file.
+        echo "FAIL (execution killed): $*"
+        exit 1
+      fi
+      sleep 1
+      NRTIMES=`expr $NRTIMES + 1`
+    done
+    STATUS=0
+  else
+    eval "$COMMAND" > ${PROG}_tmp.out
+    STATUS=$?
+  fi
+
+  # Check the status.
   case $STATUS in 
   0) 
-     if [ -f $PROG.stdout ]
-     then
-        CAT=cat
-     else
-        if [ "$NEEDOUTFIL" = 1 ]; then
-            echo "FAIL (reference output file missing): $PROG"
-	    STATUS=2
-        else
-            echo "PASS (execution succeeded): $PROG"
-        fi
-        exit
-     fi
-     ;;
+    if [ -f $PROG.stdout ]
+    then
+      CAT=cat
+    else
+      if [ "$NEEDOUTFIL" = 1 ]; then
+        echo "FAIL (reference output file missing): $PROG"
+        STATUS=2
+      else
+        echo "PASS (execution succeeded): $PROG"
+      fi
+      exit
+    fi
+    ;;
   3) 
-     echo "UNTESTED: $PROG"
-     STATUS=77
-     exit
-     ;;
+    echo "UNTESTED: $PROG"
+    STATUS=77
+    exit
+    ;;
   *) 
-     echo "FAIL (execution failure): $PROG"
-     # We may want to know what went wrong, so we'll secure the log file
-     if [ -f ${PROG}_tmp.log ]
-     then
-        mv ${PROG}_tmp.log ${PROG}.err
-     fi
-     exit
+    echo "FAIL (execution failure): $PROG"
+    # We may want to know what went wrong, so we'll secure the log file
+    if [ -f ${PROG}_tmp.log ]
+    then
+      mv ${PROG}_tmp.log ${PROG}.err
+    fi
+    exit
      ;;
   esac
 
