bug 1389: Added support for cmake

diff --git a/trunk/autoconf_share/dorubbuild b/trunk/autoconf_share/dorubbuild
--- a/trunk/autoconf_share/dorubbuild
+++ b/trunk/autoconf_share/dorubbuild
@@ -76,6 +76,8 @@ distcheck=$1
 shift
 rpm=$1
 shift
+cmake=$1
+shift
 pkgs=$*
 
 kstr=
@@ -134,7 +136,11 @@ fi
 if [ $buildmake = 1 ]; then
   mainmake="date $ksep make $kstr $jobsopt "
   if [ $bldtest = 1 ]; then
-    postmake="$ksep (if [ -d test ]; then cd test $ksep make test; fi;)"
+    if [ $cmake = 1 ]; then
+      postmake="$ksep make test"
+    else
+      postmake="$ksep (if [ -d test ]; then cd test $ksep make test; fi;)"
+    fi
   fi
   if [ $check = 1 ]; then
     if [ "$checktool" = "" ]; then
@@ -168,91 +174,107 @@ if [ "$builddir" != "." ]; then
   fi
 fi
 
-# Build the packages.
-status=0
-for pkg in $pkgs
-do
-  echo "" >> $logfile
-  if [ $skipbuilt = 1 ]; then
-    fgrep "$pkg " $resfile 2>&1 > /dev/null
-    if [ $? = 0 ]; then
-      echo "  skipping package $pkg; already built in a previous run" | tee -a $logfile
-      continue
-    fi
+# Build with cmake if told so.
+if [ $cmake = 1 ]; then
+  cd $builddir || exit 1
+  mkdir -p build/$variant >> $logfile 2>&1
+  if [ $? != 0 ]; then
+    exit 1
   fi
-  echo " *** Building package $pkg ***" | tee -a $logfile
+  cd build/$variant || exit 1
+  echo ":::::: BUILDING VARIANT $variant " >> $srcdir/$logfile
+  echo "$srcdir/CMake/makeCMakeCache $srcdir $srcdir/lofarconf.in.private CMakeCache.txt && cmake -DCMAKE_MODULE_PATH:PATH=$srcdir/CMake $srcdir && $premake $mainmake $postmake" >> $srcdir/$logfile
+  eval "($srcdir/CMake/makeCMakeCache $srcdir $srcdir/lofarconf.in.private CMakeCache.txt && cmake -DCMAKE_MODULE_PATH:PATH=$srcdir/CMake $srcdir && $premake $mainmake $postmake)" >> $srcdir/$logfile 2>&1
+  status=$?
+  echo ":::::: FINISHED BUILDING VARIANT $variant" >> $srcdir/$logfile
+else
 
-  # Create the build directory as needed.
-  pkgb=`basename $pkg`
-  if [ "$builddir" = "." ]; then
-    (cd $pkg && mkdir -p build/$variant) >> $logfile 2>&1
-    if [ $? != 0 ]; then
-      exit 1
+  # Build the packages with the autotools.
+  status=0
+  for pkg in $pkgs
+  do
+    echo "" >> $logfile
+    if [ $skipbuilt = 1 ]; then
+      fgrep "$pkg " $resfile 2>&1 > /dev/null
+      if [ $? = 0 ]; then
+        echo "  skipping package $pkg; already built in a previous run" | tee -a $logfile
+        continue
+      fi
     fi
-    blddir=$srcdir/$pkg/build/$variant
-  else
-    (cd $builddir/build/$variant && mkdir -p $pkg) >> $logfile 2>&1
-    if [ $? != 0 ]; then
-      exit 1
+    echo " *** Building package $pkg ***" | tee -a $logfile
+
+    # Create the build directory as needed.
+    pkgb=`basename $pkg`
+    if [ "$builddir" = "." ]; then
+      (cd $pkg && mkdir -p build/$variant) >> $logfile 2>&1
+      if [ $? != 0 ]; then
+        exit 1
+      fi
+      blddir=$srcdir/$pkg/build/$variant
+    else
+      (cd $builddir/build/$variant && mkdir -p $pkg) >> $logfile 2>&1
+      if [ $? != 0 ]; then
+        exit 1
+      fi
+      blddir=$builddir/build/$variant/$pkg
     fi
-    blddir=$builddir/build/$variant/$pkg
-  fi
-  initcmd="cd $blddir"
+    initcmd="cd $blddir"
 
-  # Determine new md5sum of files affecting the configure.
-  $md5pgm $srcdir/autoconf_share/variants > $blddir/conf.md5
-  lfr_host=`uname -n | sed -e "s%\..*%%"`
-  if [ -f $srcdir/autoconf_share/variants.$lfr_host ]; then
-    $md5pgm $srcdir/autoconf_share/variants.$lfr_host >> $blddir/conf.md5
-  fi
-  if [ -f $srcdir/$pkg/boot.md5 ]; then
-    $md5pgm $srcdir/$pkg/boot.md5 >> $blddir/conf.md5
-  fi
+    # Determine new md5sum of files affecting the configure.
+    $md5pgm $srcdir/autoconf_share/variants > $blddir/conf.md5
+    lfr_host=`uname -n | sed -e "s%\..*%%"`
+    if [ -f $srcdir/autoconf_share/variants.$lfr_host ]; then
+      $md5pgm $srcdir/autoconf_share/variants.$lfr_host >> $blddir/conf.md5
+    fi
+    if [ -f $srcdir/$pkg/boot.md5 ]; then
+      $md5pgm $srcdir/$pkg/boot.md5 >> $blddir/conf.md5
+    fi
 
-  # Create the various parts of the configure and make commands.
-  if [ $conf != 0 ]; then
-    # Each configure is started and ended with a special message which
-    # is used by scanbuildlog.
-    # The message is not fully composed here, because:
-    #  1. the variant name is not known here.
-    #  2. the message is not shown by the echo command prior to lofarconf.
-    # Instead variable confmsg1 is created from confmsgst prior to lofarconf.
-    confmsgst=':::::: CONFIGURING VARIANT $variant FOR PACKAGE $pkg'
-    confmsgend=':::::: FINISHED CONFIGURING VARIANT $variant FOR PACKAGE $pkg'
-    confcmd="(stat=0; chg=1; if [ $conf = 2  -a  -f conf.md5-check ]; then $md5pgm --check conf.md5-check > /dev/null 2>&1; chg="'$?'"; fi; if [ "'$chg'" = 0 ]; then echo '  package '"$pkg"' needs no configuring; md5sum has not changed'; else rm -f conf.md5-check; echo "'$confmsg1'"; $srcdir/$pkg/lofarconf $confopt && $md5pgm conf.md5 > conf.md5-check; stat="'$?; echo $confmsg2; fi; exit $stat)'" $ksep "
-  fi
-  buildmsgst=':::::: BUILDING VARIANT $variant FOR PACKAGE $pkg'
-  buildmsgend=':::::: FINISHED BUILDING VARIANT $variant FOR PACKAGE $pkg'
-  if [ $clean = 2 ]; then
-    premake="make distclean $ksep $srcdir/$pkg/lofarconf $confopt $ksep "
-  fi
-  makecmd="$premake $mainmake $postmake"
-  if [ $dist = 1 ]; then
-    makecmd="$makecmd $ksep mkdir -p $srcdir/installed/$variant/dist $ksep cp $pkgb-*.tar.gz $srcdir/installed/$variant/dist"
-  fi
-  makecmd='(echo $buildmsg1; '"$makecmd"'; stat=$?; echo $buildmsg2; exit $stat)'
-  # Log and execute the command.
-  # Generate the correct configure and build messages.
-  echo "($initcmd $ksep $confcmd $makecmd;)" >> $logfile
-  confmsg1=`eval echo $confmsgst`
-  confmsg2=`eval echo $confmsgend`
-  buildmsg1=`eval echo $buildmsgst`
-  buildmsg2=`eval echo $buildmsgend`
-  if [ $buildmake = 1 ]; then
-    eval "($initcmd $ksep $confcmd $makecmd && echo $pkg '# built at'"' `date`'" >> $srcdir/$resfile; exit "'$?)' >> $logfile 2>&1
-    stat=$?
-  else
-    eval "($initcmd $ksep $confcmd $makecmd; exit "'$?)' >> $logfile 2>&1
-    stat=$?
-  fi
-  # Stop if error and -k is not given.
-  echo "status=$stat" >> $logfile
-  if [ "$stat" != 0 ]; then
-    status=$stat
-    echo " !!! Build of package $pkg failed !!!" | tee -a $logfile
-    [ $kopt = 0 ] && break
-  fi
-done
+    # Create the various parts of the configure and make commands.
+    if [ $conf != 0 ]; then
+      # Each configure is started and ended with a special message which
+      # is used by scanbuildlog.
+      # The message is not fully composed here, because:
+      #  1. the variant name is not known here.
+      #  2. the message is not shown by the echo command prior to lofarconf.
+      # Instead variable confmsg1 is created from confmsgst prior to lofarconf.
+      confmsgst=':::::: CONFIGURING VARIANT $variant FOR PACKAGE $pkg'
+      confmsgend=':::::: FINISHED CONFIGURING VARIANT $variant FOR PACKAGE $pkg'
+      confcmd="(stat=0; chg=1; if [ $conf = 2  -a  -f conf.md5-check ]; then $md5pgm --check conf.md5-check > /dev/null 2>&1; chg="'$?'"; fi; if [ "'$chg'" = 0 ]; then echo '  package '"$pkg"' needs no configuring; md5sum has not changed'; else rm -f conf.md5-check; echo "'$confmsg1'"; $srcdir/$pkg/lofarconf $confopt && $md5pgm conf.md5 > conf.md5-check; stat="'$?; echo $confmsg2; fi; exit $stat)'" $ksep "
+    fi
+    buildmsgst=':::::: BUILDING VARIANT $variant FOR PACKAGE $pkg'
+    buildmsgend=':::::: FINISHED BUILDING VARIANT $variant FOR PACKAGE $pkg'
+    if [ $clean = 2 ]; then
+      premake="make distclean $ksep $srcdir/$pkg/lofarconf $confopt $ksep "
+    fi
+    makecmd="$premake $mainmake $postmake"
+    if [ $dist = 1 ]; then
+      makecmd="$makecmd $ksep mkdir -p $srcdir/installed/$variant/dist $ksep cp $pkgb-*.tar.gz $srcdir/installed/$variant/dist"
+    fi
+    makecmd='(echo $buildmsg1; '"$makecmd"'; stat=$?; echo $buildmsg2; exit $stat)'
+    # Log and execute the command.
+    # Generate the correct configure and build messages.
+    echo "($initcmd $ksep $confcmd $makecmd;)" >> $logfile
+    confmsg1=`eval echo $confmsgst`
+    confmsg2=`eval echo $confmsgend`
+    buildmsg1=`eval echo $buildmsgst`
+    buildmsg2=`eval echo $buildmsgend`
+    if [ $buildmake = 1 ]; then
+      eval "($initcmd $ksep $confcmd $makecmd && echo $pkg '# built at'"' `date`'" >> $srcdir/$resfile; exit "'$?)' >> $logfile 2>&1
+      stat=$?
+    else
+      eval "($initcmd $ksep $confcmd $makecmd; exit "'$?)' >> $logfile 2>&1
+      stat=$?
+    fi
+    # Stop if error and -k is not given.
+    echo "status=$stat" >> $logfile
+    if [ "$stat" != 0 ]; then
+      status=$stat
+      echo " !!! Build of package $pkg failed !!!" | tee -a $logfile
+      [ $kopt = 0 ] && break
+    fi
+  done
+fi
 
 if [ "$status" != 0 ]; then
   echo " Error during build on `uname -n` (see $logfile for details)" | tee -a $srcdir/build.log
