bug 1419: Added -killonfail option to startdistproc. Created runlogpid to log the pid and exit status of a remote process.

diff --git a/CEP/MWCommon/src/socketrun b/CEP/MWCommon/src/socketrun
--- a/CEP/MWCommon/src/socketrun
+++ b/CEP/MWCommon/src/socketrun
@@ -33,7 +33,8 @@
 # This script is a helper script for startdistproc, but it could be used
 # stand-alone as well.
 #
-# run as: socketrun dry hfn masterhost port wait logfile program [arg1 arg2 ...]
+# run as: socketrun dry hfn masterhost port wait killfail logfile program envfile
+#                   [arg1 arg2 ...]
 #
 #   dry!=0      means that the command is only printed, not executed.
 #   hfn         is the name of an MPI-style machinefile. Each line in it
@@ -50,9 +51,12 @@
 #               E.g. mwimager only starts distributed processes, but they do
 #               not communicate, so there is no master.
 #   wait=1      means that socketrun waits for all processes to end.
+#   killfail=1  means that all other remote processes are killed if one fails.
+#               It is only used if wait=1.
 #   logfile     name of the log file to use; It will be suffixed with '-rank'
 #               where rank is the process rank.
 #   program     name of the program to start.
+#   envfile     name of the envfile generated by startdistproc.
 #   arg-i       extra arguments directly passed to the program started.
 #
 # The processes are started with the following fixed arguments:
@@ -77,9 +81,13 @@ port=$1
 shift
 wait=$1
 shift
+killfail=$1
+shift
 logfile=$1
 shift
 program=$1
+shift
+envfile=$1
 shift
 
 np=`wc -l $hfn | awk '{print $1}'`
@@ -112,12 +120,12 @@ do
   do
     arg="$arg '$a'"
   done
-  echo "ssh -x -n $host $program socket $masterhost $port $np $rank '$part' '$fsys' '$partvds' $arg" " &"
-  if test $dry = 0; then
+  echo "ssh -x -n $host $program socket $masterhost $port $np $rank '$part' '$fsys' '$partvds' '$envfile' $arg" " &"
+  if test "$dry" = 0; then
     if test "$logfile" = ""; then
-      ssh -x -n $host $program socket $masterhost $port $np $rank "$part" "$fsys" "$partvds" $arg &
+      ssh -x -n $host $program socket $masterhost $port $np $rank "$part" "$fsys" "$partvds" $envfile $arg &
     else
-      ssh -x -n $host $program socket $masterhost $port $np $rank "$part" "$fsys" "$partvds" $arg > $logfile-$rank 2>&1 &
+      ssh -x -n $host $program socket $masterhost $port $np $rank "$part" "$fsys" "$partvds" $envfile $arg > $logfile-$rank 2>&1 &
     fi
     pidlist="$pidlist $!"
   fi
@@ -125,11 +133,56 @@ do
 done
 
 # If needed, wait for the processes to end.
-status=0
+# If a process ended unsuccessfully, kill the others if needed.
 if test "$wait" = 1; then
+  if test $killfail = 1; then
+    # If killonfail, wait for the first process to end.
+    # Poll every second.
+    cont=1
+    while test $cont = 1
+    do
+      sleep 1
+      seqnr=0
+      for pid in $pidlist
+      do
+        if ! kill -0 $pid > /dev/null 2>&1; then
+          cont=0
+          break
+        fi
+        seqnr=`expr $seqnr + 1`
+      done
+    done
+    status=0
+    if test -f $envfile.pid-$seqnr; then
+      status=`grep '^status=' $envfile.pid-$seqnr | sed -e 's/status=//'`
+    fi
+    if test $status != 0; then
+      echo "Remote process (pid=$pid) with rank $seqnr ended with error status $status"
+      echo "Killing the other remote processes ..."
+      rank=0
+      for inline in `cat $hfn`
+      do
+        if test $rank != $seqnr  -a  -f $envfile.pid-$rank; then
+          host=`echo $inline | awk -F'#' '{print $1'}`
+          rempid=`grep '^pid=' $envfile.pid-$rank | sed -e 's/pid=//'`
+          echo "ssh -x $host kill -9 $rempid"
+          if test "$logfile" = ""; then
+            ssh -x $host kill -9 $rempid
+          else
+            ssh -x $host kill -9 $rempid >> $logfile-$rank
+          fi
+        fi
+        rank=`expr $rank + 1`
+      done
+    fi
+  fi
+  # Wait for all processes.
+  # Ignore status in case the pid does not exist anymore (error 127).
   for pid in $pidlist
   do
-    if ! wait $pid; then
+    wait $pid > /dev/null 2>&1
+    stat=$?
+    if test $stat != 0  -a  $stat != 127; then
       status=1
     fi
   done
