Task #4689: Merged trunk into release branch, and modified StaticMetaData files and createFiles script to enable switch between BG and Cobalt

diff --git a/branches/MAC-Task4689/MAC/APL/APLCommon/src/swlevel b/branches/MAC-Task4689/MAC/APL/APLCommon/src/swlevel
--- a/branches/MAC-Task4689/MAC/APL/APLCommon/src/swlevel
+++ b/branches/MAC-Task4689/MAC/APL/APLCommon/src/swlevel
@@ -51,6 +51,7 @@ SyntaxError()
 	echo ""
 	echo "Syntax: $(basename $0) [-s/S/v/V] [-i x] [-r/q processname] [-l][ 0 |1 |2 |3 |4 |5 |6 ]"
 	echo "-s: Show current level, exit (-S: only print number)"
+	echo "-p: Print last set level from logfile (-P: only print number)"
 	echo "-v: Show running LOFAR version, exit (-V: only print version)"
 	echo "-i: Load RSP firmware from image [x] (default image is 1)"
         echo "-l: Set to level as provided (optional)"
@@ -99,36 +100,39 @@ findImage()
 }       
 
 #
-# selectImage(); the image to load has been set in parameter $image in MAIN
+# selectImage(); load an image on the RSP boards
 #
 selectImage()
 {
 	let nrRSPs=`grep RSPBOARDS ${ETCDIR}/RemoteStation.conf | cut -d'=' -f2 | sed 's/ //g'`
 	let board=0
+        # Assume no errors with board communication
+	boardError=0
+	# Make sure we have an image number in parameter $image
+        if [ -z $image ] && [ $imageForced -eq 0 ]; then  
+            findImage `hostname -s`
+        fi
+
 	while [ $board -lt $nrRSPs ]
 	do
-		# get version number of RSPboard in var. rsu
+		# get major version of active firmware on RSPboard $board
 		boardHex=`echo $board | awk '{ printf "%02x", $1 }'`
 		rsu=`sudo ${BINDIR}/../sbin/rsuctl3 -m 10:fa:00:00:$boardHex:00 -qV 2>&1 | grep BP | cut -d':' -f2 | sed 's/ //g' | cut -d'.' -f1`
-		if [ $imageForced ] || [ ${rsu} -eq 1 ]; then
-  		  let version=$rsu
-                  # Find image location for this station
-                  if [ -z $image ]; then  
-                     findImage `hostname -s`
-                  fi
- 		  # if board has reset itself to image 0, load default RSP image again
-		  echo "Loading image $image on RSPboard $board ..."
-		  sudo ${BINDIR}/../sbin/rsuctl3_reset -m 10:fa:00:00:$boardHex:00 -q -x -p $image 1>/dev/null 2>&1
-		  #fi
-                elif [ ${rsu} -eq 6 ]; then
-		  echo "No need to reload image for RSPboard $board"
-		elif [ ${#rsu} -ne 1 ]; then 
-                  echo "No RSPboard $board found"
+
+		# If not a single number, something weird  must have happened
+		if [ ${#rsu} -ne 1 ]; then 
+                  echo "RSPboard $board: Error requesting active firmware version (communication error)"
+		  boardError=1
                 else
-                  echo "Not a valid image found for RSPboard $board; perhaps an image is being loaded"
+  		  echo "Loading image $image on RSPboard $board ..."
+		  sudo ${BINDIR}/../sbin/rsuctl3_reset -m 10:fa:00:00:$boardHex:00 -q -x -p $image 1>/dev/null 2>&1
 		fi
+		# Next board
 		let board+=1
 	done
+	if [ $boardError -eq 1 ]; then
+	    echo "One or more boards have a communication problem; try reset the 48V"
+	fi
 }
 
 #
@@ -461,6 +465,27 @@ show_level()
         exit $level
 }
 
+print_level()
+{
+        if [ -e /tmp/level.admin ]; then
+          level=`cat /tmp/level.admin`
+	  if [ "$1" != "P" ]; then
+	     echo -n "Last set level is "
+	  fi
+	  echo $level
+          if [ "$1" = "P" -o "$1" = "p" ]; then
+            exit
+          fi
+        else
+          level=-1
+          if [ "$1" != "S" ]; then
+             echo "Last set level unknown"
+          fi
+        fi
+        # argument -s/-S only returns level, no list
+        exit $level
+}
+
 show_lofar_version()
 {
         if [ -e /opt/lofar/Version.txt ]; then
@@ -486,17 +511,25 @@ handle_args()
 {
 
   # Handle arguments
-  while getopts  "hSsVvi:l:q:r:" flag
+  if [ ${#} -gt 1 ]; then
+      if [[ $1 != \-* ]]; then
+        echo "Warning: all arguments except level $1 will be ignored"
+      fi
+  fi
+  while getopts  "hSsPpVvi:l:q:r:" flag
   do
     case "$flag" in
     [sS])
     show_level $flag
     ;;
+    [pP])
+    print_level $flag
+    ;;
     [vV])
     show_lofar_version $flag
     ;;
     i)
-    imageForced=true
+    imageForced=1
     image=$OPTARG
     # This is needed to be able to retrieve the requested swlevel
     # when it is not provided with option -l
@@ -562,7 +595,7 @@ fi
 
 user=`id | cut -d'(' -f2 | cut -d')' -f1`
 group=`groups | awk '{print $1}'`
-imageForced=false
+imageForced=0
 
 handle_args $*
 
