%[ER:27]% Stricter syntax checking and update for record layer.

diff --git a/LCS/databases/PLGEN/src/genDBbase b/LCS/databases/PLGEN/src/genDBbase
--- a/LCS/databases/PLGEN/src/genDBbase
+++ b/LCS/databases/PLGEN/src/genDBbase
@@ -28,7 +28,7 @@
 #
 # $Id$
 #
-VERSION="v1.7"
+VERSION="v1.8"
 DEBUGMODE=false
 
 #---------------------------- Global routines ---------------------------------
@@ -40,7 +40,11 @@ DEBUGMODE=false
 initResultFile()
 {
 	echo -n "# This file was generated by genDBbase ${VERSION} on " ; date
-	echo "# with the command: genDBbase ${MODULE} <precompiled_headerfiles>"
+	if [ ${#HEADERFILES}+${#COMMAND} -gt 55 ]; then
+		echo "# with the command: ${COMMAND} <precompiled_headerfiles>"
+	else
+		echo "# with the command: ${COMMAND} ${HEADERFILES}"
+	fi
 	echo -n "# from the directory: " ; pwd
 	echo "#"
 	echo "# PLEASE COMPLETE THIS FILE AND REMOVE THE .proto EXTENSION"
@@ -539,6 +543,7 @@ addToMapFile()
 		ColumnType=resolveVariableType(PlainMemberType)	# First try B
 		if (substr(ColumnType,1,3) != "@@@") {			# familiar type?
 			ColumnName=toupper(MemberName)
+			gsub("^ITS", "", ColumnName)				# strip leading "ITS"
 			if (ColumnType == "VARCHAR") {
 				ColumnType=ColumnType "(" ArrSize ")"
 			}
@@ -644,51 +649,136 @@ addToMapFile()
 constructFunfile()
 {
 	grep -v "#" $1 | sort | uniq | awk '{
-		printf "%-15s		I\n", $1
-		printf "%-15s		U\n", $1
-		printf "%-15s		D\n", $1
-		printf "%-15s		S    WHERE ???\n", $1
+		printf "%-15s	I   insert%s\n", $1, $1
+		printf "%-15s	U   update%s	WHERE @@@\n", $1, $1
+		printf "%-15s	D   delete%s	WHERE @@@\n", $1, $1
+		printf "%-15s	S   search%s	WHERE @@@\n", $1, $1
 	}'
 }
 
-#------------------------------- MAIN ----------------------------------------
+#-------------------- General subroutines --------------------
 #
-# Syntax: genDBbase [-d destdir] module precompiled_headerfiles
+# Fail msg
 #
+# Shows the message on stdout and exits
+Fail()
+{
+	echo "FAIL: $*"
+	cleanupWorkFiles
+	exit 1
+}
 
-DESTDIR="."
+#
+# ControlledFileDeletion FileName
+#
+# Asks the user if the file may be removed. If not the program is terminated.
+# When the FORCE option is on the file is removed without interference of the user.
+ControlledFileDeletion()
+{
+	FileName=$1
+
+	# Does file exist
+	if [ ! -f "${FileName}" ]; then
+		return
+	fi
+
+	# If FORCE option is off let the user decide.
+	if [ "${FORCE}" != "true" ]; then
+		ready=false
+		while [ "$ready" == "false" ]
+		do
+			echo -n "Targetfile ${FileName} already exists, remove it (y/n)? "
+			read answer
+			case $answer in
+			y|Y|yes|Yes)	ready=true
+							;;
+			n|N|no|No)		Fail "Target ${FileName}.i may not be overwritten"
+							;;
+			esac
+		done
+	fi
+	echo "Removing file ${FileName}"
+	rm -f ${FileName}
+}
+
+#
+# SyntaxError msg
+#
+# Shows the right syntax on stdout with the given message.
+# Exists afterwards.
+SyntaxError()
+{
+	Msg=$1
+
+	[ -z "${Msg}" ] || echo "ERROR: ${Msg}"
+	echo "Syntax: $(basename $0) [-d destdir] [-t target] [-f] precompiled_headerfile(s)"
+	echo "    destdir   Relative directory where the map and functionfile are placed"
+	echo "    target    First part of the name of the map and functionfile"
+	echo "    -f        Force removal of target(s) if it already exists"
+	echo ""
+	exit 1
+}
+
+#------------------------------- MAIN program --------------------------------
+#
+# Syntax: genDBbase [-d destdir] [-t target] [-f] precompiled_headerfiles
+#
 
 # Check invocation syntax
 #
-eval set argv=`getopt "d:" $*`			# reformat arguments
+DESTDIR="."
+FORCE=false
+TARGET=""
+COMMAND=$(basename $0)
+eval set argv=`getopt "d:t:f" $*`			# reformat arguments
 shift
-case "$1" in
-	-d) DESTDIR=$2
-		if [ ! -d ${DESTDIR} ]; then
-			echo "Destination directory >${DESTDIR}< does not exist"
-			exit 1
-		fi
-		shift 2
-		;;
-esac
+while [ "$1" != "--" ]
+do
+	case "$1" in
+		-d) DESTDIR=$2
+			[ -d ${DESTDIR} ] ||
+				SyntaxError "Destination directory >${DESTDIR}< does not exist"
+			shift 2
+			COMMAND="${COMMAND} -d ${DESTDIR}"
+			;;
+		-t)	TARGET=$2
+			shift 2
+			COMMAND="${COMMAND} -t ${TARGET}"
+			;;
+		-f)	FORCE=true
+			shift 1
+			COMMAND="${COMMAND} -f"
+			;;
+	esac
+done
 shift									# remove --
 
-case $# in
-	0|1)	echo "Syntax: $0 [-d destdir] module precompiled_headerfiles"
-		exit 0
-		;;
-	*)	MODULE=$1
-		shift
-		HEADERFILES="$*"
-		;;
-esac
+# Need at least one precompfile
+[ $# -ge 1 ] || SyntaxError "Need at least one precompiled headerfile."
+
+# All precompfiles must exist
+for file in $*
+do
+	[ -s ${file} ] || SyntaxError "File ${file} doesn't exist"
+done
+
+# When target is empty use name of 1st precompfile as a base.
+[ -z "${TARGET}" ] && TARGET=`echo $1 | cut -d"." -f1`
+
+# construct name of targetfiles
+MAPFILE=${DESTDIR}/${TARGET}.plmap.proto		# resultfile
+FUNFILE=${DESTDIR}/${TARGET}.plfun.proto		# resultfile
+
+# If targets exist, let the user or the FORCE option decide what to do
+ControlledFileDeletion ${MAPFILE}
+ControlledFileDeletion ${FUNFILE}
+
+# All arguments seem ok, continue porcessing
 
 # Initialize some variables
-#
-MAPFILE=${DESTDIR}/${MODULE}.map.proto		# resultfile
-FUNFILE=${DESTDIR}/${MODULE}.fun.proto		# resultfile
+HEADERFILES="$*"
 
-# A lot of temp files but this makes life much easier
+# An awfull lot of temp files but this makes life much easier
 ADDINGWORKFILE=/tmp/adding.LCS.$$			# subclasses curr. adding
 FUNCTIONWORKFILE=/tmp/functions.LCS.$$		# functions in the inputfile
 GREPWORKFILE=/tmp/grep.LCS.$$				# tmp grep result
@@ -704,13 +794,13 @@ MODCLASSWRKFILE=/tmp/classes.LCS.$$			# all classes define in the .i file
 cleanupWorkFiles
 
 # Set trap handler before we create anything
-trap "cleanupWorkFiles ; exit" 1 2 3 13 15
+trap "cleanupWorkFiles ; exit" 1 2 3 6 9 13 15
 
 # Write headers to the result files.
-initResultFile  	> ${MAPFILE}
-initResultFile  	> ${FUNFILE}
+initResultFile 	> ${MAPFILE}
+initResultFile 	> ${FUNFILE}
 
-echo "Creating file ${MAPFILE}"
+echo "Creating file ${MAPFILE} ..."
 # Scan the precompiled_headerfiles and substract the class hierarchy
 for file in ${HEADERFILES}
 do
