Task #4887: Merged trunk into the branch

diff --git a/branches/Cobalt-Task4887/RTCP/Cobalt/InputProc/src/mpirun.sh.in b/branches/Cobalt-Task4887/RTCP/Cobalt/InputProc/src/mpirun.sh.in
--- a/branches/Cobalt-Task4887/RTCP/Cobalt/InputProc/src/mpirun.sh.in
+++ b/branches/Cobalt-Task4887/RTCP/Cobalt/InputProc/src/mpirun.sh.in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Script to start MPI. It tries to wrap (part of) the different scripts that
 # exist to start MPI (e.g., mpirun, mpiexec, etc.)
@@ -8,6 +8,8 @@ error()
   echo "ERROR: $@"
   exit 1
 }
+
+declare -A ENVVARS
 
 parse_options()
 {
@@ -25,6 +27,16 @@ parse_options()
         # comma-separated host list
         HOSTS="$2"
         shift 2 || error "argument for option $1 missing"
+        ;;
+      -x)
+        # environment variable to marshall,
+        # we only support the VAR=VALUE format
+        KEYVAL="$2"
+        shift 2 || error "argument for option $1 missing"
+
+        KEY=`echo "$KEYVAL" | cut -d= -f1`
+        VAL=`echo "$KEYVAL" | cut -d= -f2-`
+        ENVVARS["$KEY"]="$VAL"
         ;;
       -*)
         error "$1 is an unknown option"
@@ -44,6 +56,13 @@ set_nompi_options()
 {
   # Ignore all mpirun options
   :
+
+  for KEY in "${!ENVVARS[*]}"
+  do
+    VAL=${ENVVARS[$KEY]}
+
+    export $KEY="$VAL"
+  done
 }
 
 set_openmpi_options()
@@ -57,6 +76,13 @@ set_openmpi_options()
   then
     MPIEXEC_PREFLAGS="$MPIEXEC_PREFLAGS -H $HOSTS"
   fi
+
+  for KEY in "${!ENVVARS[*]}"
+  do
+    VAL=${ENVVARS[$KEY]}
+
+    MPIEXEC_PREFLAGS="$MPIEXEC_PREFLAGS -x $KEY=$VAL"
+  done
 }
 
 set_mvapich2_options()
@@ -70,6 +96,13 @@ set_mvapich2_options()
   then
     MPIEXEC_PREFLAGS="$MPIEXEC_PREFLAGS -hosts $HOSTS"
   fi
+
+  for KEY in "${!ENVVARS[*]}"
+  do
+    VAL=${ENVVARS[$KEY]}
+
+    MPIEXEC_PREFLAGS="$MPIEXEC_PREFLAGS -env $KEY $VAL"
+  done
 }
 
 if [ "@HAVE_MPI@" = "TRUE" ]
