%[ER:27]% Major update to support the R-layer also. Added check on overwriting the target-files.

diff --git a/trunk/LCS/databases/PL/scripts/genDBsql b/trunk/LCS/databases/PL/scripts/genDBsql
--- a/trunk/LCS/databases/PL/scripts/genDBsql
+++ b/trunk/LCS/databases/PL/scripts/genDBsql
@@ -28,7 +28,8 @@
 #
 # $Id$
 #
-VERSION="v1.5"
+VERSION="v1.6"
+DEBUGMODE=false
 
 #---------------------------- Global routines ---------------------------------
 #
@@ -52,7 +53,7 @@ initTmpfile()
 initSQLfile()
 {
 	echo -n "-- This file was generated by genDBsql ${VERSION} on " ; date
-	echo "-- with the command: genDBsql ${MODULE}"
+	echo "-- with the command: ${COMMAND} ${LAYER} ${MAPFILE}"
 	echo -n "-- from the directory: " ; pwd
 	echo "--"
 	echo "-- EDITING THIS FILE MANUALLY IS AT YOUR OWN RISK"
@@ -60,8 +61,8 @@ initSQLfile()
 	echo "--"
 
 	if [ "$1" == "m" ]; then
-		echo "-- When you run this file all databasetables for module $2"
-		echo "-- are created."
+		echo "-- When you run this file all databasetables for the"
+		echo "-- sources listed below are created."
 		echo "--"
 		echo "-- WARNING: EXISTING TABLES ARE DROPPED BEFORE CREATION!!!"
 		echo "--"
@@ -95,7 +96,7 @@ initSQLfile()
 #	MemberName may be of the form X::y or X.y when the user merged some 
 #			   tables manually
 #
-# NOTE: THIS ROUTINE ALSO EXISTS IN genDBsql
+# NOTE: THIS ROUTINE ALSO EXISTS IN genDBcode
 #
 convertMapfile()
 {
@@ -147,10 +148,17 @@ addCreateTableCommand()
 
 	echo "drop table ${Table};"
 	echo "create table ${Table} ("
-	echo    "	ObjId		BIGINT		NOT NULL UNIQUE PRIMARY KEY,"
-	echo    "	Owner		BIGINT		NOT	NULL,"
-	echo -n "	VersionNr	INTEGER		NOT NULL"
+	# P layer always starts with 3 administrative fields
+	if [ "${LAYER}" == "P" ]; then
+		echo    "	ObjId		BIGINT		NOT NULL UNIQUE PRIMARY KEY,"
+		echo    "	Owner		BIGINT		NOT	NULL,"
+		echo -n "	VersionNr	INTEGER		NOT NULL"
+		firstLine=false
+	else
+		firstLine=true
+	fi
 	
+	# scan mapfile for all fields of the current table
 	cleanlist ${MAPWORKFILE} | grep "!${Table}!" | while read line
 	do
 		TableName=`echo $line | cut -d'!' -f2`
@@ -160,9 +168,11 @@ addCreateTableCommand()
 
 		ColumnName=`echo $line | cut -d'!' -f6`
 		ColumnType=`echo $line | cut -d'!' -f8`
+		# Add only 'plain' fields
 		if [ "${ColumnName}" != "Class" -a "${ColumnName}" != "BaseClass" ]; then
-			echo ","
+			[ "${firstLine}" == "false" ] && echo ","
 			echo -n "	${ColumnName}	${ColumnType}"
+			firstLine=false
 		fi
 	done
 
@@ -170,11 +180,18 @@ addCreateTableCommand()
 	echo ""
 
 }
+
 #
 # addCreateTriggerCommand tablename
 #
+# A trigger must be defined for tables in the P layer. This trigger will 
+# update the VersionNr field and may prevent an update when the VersionNr
+# doesnot match the one in the database.
+#
 addCreateTriggerCommand()
 {
+	[ "${LAYER}" == "R" ] && return;		# only for P layer
+
 	Table=$1
 
 	echo "CREATE TRIGGER ${Table}UpdateVersionNr BEFORE INSERT OR UPDATE ON ${Table}"
@@ -189,7 +206,11 @@ addCreateTriggerCommand()
 #
 cleanupWorkFiles()
 {
-	rm -f ${MAPWORKFILE}
+	if [ "${DEBUGMODE}" != "true" ]; then
+		rm -f ${MAPWORKFILE} ${ALLFILESWRKFILE}
+	else
+		echo "DEBUGMODE, NOT REMOVING TEMPFILES in /tmp"
+	fi
 }
 
 #
@@ -202,49 +223,118 @@ cleanlist()
 	cut -d"#" -f1 $1 | awk '{ if (NF > 0) print $0 }'
 }
 
+#
+# ControlledFileDeletion FileName
+#
+# Asks the user if the file may be removed. If not the program is terminated.
+# When the FORCE option is on the file is removed without interference of the user.
+ControlledFileDeletion()
+{
+	FileName=$1
+
+	# Does file exist
+	if [ ! -f "${FileName}" ]; then
+		return
+	fi
+
+	# If FORCE option is off let the user decide.
+	if [ "${FORCE}" != "true" ]; then
+		ready=false
+		while [ "$ready" == "false" ]
+		do
+			echo -n "Targetfile ${FileName} already exists, remove it (y/n)? "
+			read answer
+			case $answer in
+			y|Y|yes|Yes)	ready=true
+							;;
+			n|N|no|No)		Fail "Target ${FileName} may not be overwritten"
+							;;
+			esac
+		done
+	fi
+	echo "Removing file ${FileName}"
+	rm -f ${FileName}
+}
+
+#
+# Fail msg
+#
+# Shows the message on stdout and exits
+Fail()
+{
+	echo "FAIL: $*"
+	cleanupWorkFiles
+	exit 1
+}
+
+#
+# SyntaxError msg
+#
+# Shows the right syntax on stdout together with the given msg.
+# Exits afterwards.
+SyntaxError()
+{
+	Msg=$1
+
+	[ -z "${Msg}" ] || echo "ERROR: ${Msg}"
+	echo "Syntax: $(basename $0) [-d destdir] [-f] layer mapfile"
+	echo "  layer: R(ecord) or P(ersistency)"
+	echo "    -f   Force removal of target(s) if it already exists"
+	echo ""
+	exit 1
+}
 
 #------------------------------- MAIN program ---------------------------------
 #
-# Check invocation syntax: genDBsql [-d destdir] mapfile
+# Syntax: genDBsql [-d destdir] [-f] P|R mapfile
 #
-
-# Check option argument
+# Check invocation syntax
 DESTDIR="."							# assume no destination directory
-eval set argv=`getopt "d:" $*`		# reformat arguments
-shift
-case "$1" in
-	-d)	DESTDIR=$2
-		if [ ! -d ${DESTDIR} ]; then
-			echo "Destination directory >${DESTDIR}< does not exist"
-			exit 1
-		fi
-		shift 2
-		;;
-esac
+FORCE=false							# do not overwrite existing files
+COMMAND=$(basename $0)				# reconstruction of the commandline
+
+eval set argv=`getopt "d:f" $*`		# reformat arguments
+shift								# cut off programname
+while [ "$1" != "--" ]
+do
+	case "$1" in
+		-d)	DESTDIR=$2
+			if [ ! -d ${DESTDIR} ]; then
+				echo "Destination directory >${DESTDIR}< does not exist"
+				exit 1
+			fi
+			shift 2
+			COMMAND="${COMMAND} -d ${DESTDIR}"
+			;;
+		-f) FORCE=true
+			shift 1
+			COMMAND="${COMMAND} -f"
+			;;
+		esac
+done
 shift								# remove --
 
-# Check other arguments
-case $# in
-	1)	MAPFILE=$1
-		MODULE=`echo ${MAPFILE} | cut -d"." -f1`
-		;;
-	*)	echo "Syntax: $0 [-d destdir] mapfile"
-		exit 0
-		;;
+# Need at least two arguments
+[ $# -eq 2 ] || SyntaxError "Need the layer argument and the mapfilename."
+
+typeset -u LAYER=$1
+MAPFILE=$2
+
+# Check layer type
+case "${LAYER}" in
+R)		PREFIX="Rec"	;;
+P)		PREFIX="PO_"	;;
+*)		SyntaxError "Layer should be R(ecord) or P(ersistency), not >${LAYER}<"
 esac
 
 # Mapfile must exist
-#
-if [ ! -s ${MAPFILE} ]; then
-    echo "File ${MAPFILE} doesn't exist\n"
-    exit 1
-fi
+[ -s ${MAPFILE} ] || SyntaxError "File ${MAPFILE} doesn't exist"
 
 # Initialize some variables
-#
+ALLFILESWRKFILE=/tmp/allfiles.LCS.$$
+CLASSLOCATIONWRKFILE=/dev/null				# to satisfy convertMapfile
 MAPWORKFILE=/tmp/mapinfo.sql.LCS.$$
-MODULEFILE=${DESTDIR}/${MODULE}_create_databases.sql
-CLASSLOCATIONWRKFILE=/dev/null
+MODULEFILE=${DESTDIR}/${PREFIX}create_databases.sql
 
 # Make sure there are no old workfiles left
 cleanupWorkFiles
@@ -255,22 +345,42 @@ trap "cleanupWorkFiles ; exit" 1 2 3 13 15
 # initialize the files we have to create.
 initTmpfile					> ${MAPWORKFILE}
 convertMapfile ${MAPFILE}	>>${MAPWORKFILE}
-initSQLfile m ${MODULE}		> ${MODULEFILE}
+
+# Now the converted mapfile exists we can check for file duplicates.
+# If targets exist, let the user or the FORCE option decide what to do
+# Note: we have to do this a bit clumsy because ControlledFileDeletion
+#	does a 'read' and 'read's may not be nested.
+cleanlist ${MAPWORKFILE} | cut -d'!' -f9 | sed "s/\.h$//" >>${ALLFILESWRKFILE}
+while [ -s ${ALLFILESWRKFILE} ]
+do
+	File=`head -1 ${ALLFILESWRKFILE}`
+	ControlledFileDeletion ${DESTDIR}/${PREFIX}${File}.sql
+	sed "1,1D" ${ALLFILESWRKFILE} >>${ALLFILESWRKFILE}2
+	mv ${ALLFILESWRKFILE}2 ${ALLFILESWRKFILE}
+done
+ControlledFileDeletion ${MODULEFILE}
+
+# Once we are here we are allowed to overwrite all targetfiles.
+initSQLfile m 				> ${MODULEFILE}
 
 # Scan the functionfile to determine what code should be generated
-#
 PrevTable="Unknown"
 cleanlist ${MAPWORKFILE} | while read line
 do
 	ClassName=`echo $line | cut -d'!' -f1`
 	TableName=`echo $line | cut -d'!' -f2`
-	if [ "${TableName}" != "${PrevTable}" ]; then	# new table?
-		SQLFILE=${DESTDIR}/${ClassName}.sql
+	FileName=`echo $line | cut -d'!' -f9 | sed "s/\.h$//"`
+	SQLFILE=${DESTDIR}/${PREFIX}${FileName}.sql
+	# Create file if it does not exists yet.
+	if [ ! -f "${SQLFILE}" ]; then
 		echo "Creating file ${SQLFILE}"
 		initSQLfile c ${ClassName}				  >${SQLFILE}
+		echo "\i " $(basename ${SQLFILE})		 >>${MODULEFILE}
+	fi
+	# Add code for this table
+	if [ "${PrevTable}" != "${TableName}" ]; then
 		addCreateTableCommand ${TableName} 		 >>${SQLFILE}
 		addCreateTriggerCommand ${TableName}	 >>${SQLFILE}
-		echo "\i ${SQLFILE}"					 >>${MODULEFILE}
 		PrevTable=${TableName}
 	fi
 done
