%[ER:27]% Stricter syntax checking and target may be omitted.

diff --git a/trunk/LCS/databases/PL/scripts/genDBi b/trunk/LCS/databases/PL/scripts/genDBi
--- a/trunk/LCS/databases/PL/scripts/genDBi
+++ b/trunk/LCS/databases/PL/scripts/genDBi
@@ -28,7 +28,7 @@
 #
 # $Id$
 #
-VERSION="v1.0"
+VERSION="v1.1"
 DEBUGMODE=false
 
 #
@@ -45,6 +45,7 @@ cleanupWorkFiles()
 	fi
 }
 
+#
 # Fail msg
 #
 # Shows the message on stdout and exits
@@ -55,7 +56,40 @@ Fail()
 	exit 1
 }
 
+#
+# ControlledFileDeletion FileName
+#
+# Asks the user if the file may be removed. If not the program is terminated.
+# When the FORCE option is on the file is removed without interference of the user.
+ControlledFileDeletion()
+{
+	FileName=$1
 
+	# Does file exist
+	if [ ! -f "${FileName}" ]; then
+		return
+	fi
+
+	# If FORCE option is off let the user decide.
+	if [ "${FORCE}" != "true" ]; then
+		ready=false
+		while [ "$ready" == "false" ]
+		do
+			echo -n "Targetfile ${FileName} already exists, remove it (y/n)? "
+			read answer
+			case $answer in
+			y|Y|yes|Yes)	ready=true
+							;;
+			n|N|no|No)		Fail "Target ${FileName}.i may not be overwritten"
+							;;
+			esac
+		done
+	fi
+	echo "Removing file ${FileName}"
+	rm -f ${FileName}
+}
+
+#
 # SyntaxError msg
 #
 # Shows the right syntax on stdout together with the given msg.
@@ -64,12 +98,13 @@ SyntaxError()
 {
 	Msg=$1
 
-	[ "X${Msg}" != "X" ] && echo "ERROR: ${Msg}"
+	[ -z "${Msg}" ] || echo "ERROR: ${Msg}"
 	echo "Syntax: $(basename $0) [-d destdir] [-b builddir] [-t target] [-f] headerfile(s)"
-	echo "    destdir	relative directory where .i file is placed, e.g. './generated'"
-	echo "    builddir	directory where .precomplie is done, e.g. 'gnu_opt'"
-	echo "    target	name of the .i file to create, e.g. 'myProject'"
+	echo "    destdir	Relative directory where .i file is placed, e.g. './generated'"
+	echo "    builddir	Directory where .precomplie is done, e.g. 'gnu_opt'"
+	echo "    target	Name of the .i file to create, e.g. 'myProject'"
 	echo "    -f    	Force removal of target if it already exists"
+	echo ""
 	exit 1
 }
 
@@ -86,7 +121,7 @@ PRECOMPFILE="tmp_${TimeStamp}.i"
 BUILDDIRWRKFILE="/tmp/BuildDir.LCS.$$"
 
 # Check option argument
-DESTDIR="."							# assume no destination directory
+DESTDIR="."								# assume no destination directory
 BUILDDIR=""
 TARGET=""
 FORCE=false
@@ -97,13 +132,13 @@ do
 	case "$1" in
 		-d)	DESTDIR=$2
 			[ -d ${DESTDIR} ] || 
-					SyntaxError "Destination directory >${DESTDIR}< does not exist"
+				SyntaxError "Destination directory >${DESTDIR}< does not exist"
 			shift 2
 			;;
 		-b)	BUILDDIR=$2
 			shift 2
 			;;
-		-t)	TARGET=`echo $2 | sed "s/\.i$//"`		# strip off trailing .i
+		-t)	TARGET=`echo $2.i | sed "s/\.i\.i$/\.i/"`	# strip off trailing .i
 			shift 2
 			;;
 		-f) FORCE=true
@@ -122,25 +157,11 @@ do
 	[ -s ${file} ] || SyntaxError "File ${file} doesn't exist"
 done
 
-# Check if target file already exist and let the user decide.
-if [ -f "${DESTDIR}/${TARGET}.i" ]; then
-	if [ "${FORCE}" != "true" ]; then
-		ready=false
-		while [ "$ready" == "false" ]
-		do
-			echo -n "Targetfile ${DESTDIR}/${TARGET}.i already exists, remove it (y/n)? "
-			read answer
-			case $answer in
-			y|Y|yes|Yes)	FORCE=true
-							ready=true
-							;;
-			n|N|no|No)		Fail "Target ${DESTDIR}/${TARGET}.i may not be overwritten"
-							;;
-			esac
-		done
-	fi
-	rm -f ${DESTDIR}/${TARGET}.i
-fi
+# When target is empty use name (w/o .h) as target.
+[ -z "${TARGET}" ] && TARGET=`echo $1.i | sed "s/\.h\.i$/\.i/"`
+
+# If target file already exist, let the user decide when FORCE is off.
+ControlledFileDeletion ${DESTDIR}/${TARGET}
 
 # All arguments seem ok, continue processing
 
@@ -160,15 +181,15 @@ done
 LeafDir=$(basename $SOURCEDIR)
 
 # Try to cd to the build directory
-cd ../build 2>/dev/null
+cd ../build 2>/dev/null								# assume one level deep
 if [ $? -ne 0 ]; then
-	cd ../../build 2>/dev/null
+	cd ../../build 2>/dev/null						# try two levels
 	[ $? -eq 0 ] || Fail "Cannot find the build directory in ../ or ../../"
 fi
 
 # We are in the build directory.
 # Try to cd to the same leaf directory
-if [ -n "${BUILDDIR}" ]; then
+if [ -n "${BUILDDIR}" ]; then						# user specified the builddir?
 	theBuildDir=${BUILDDIR}/${LeafDir}
 else
 	`ls -1d */${LeafDir} >${BUILDDIRWRKFILE}`
@@ -187,12 +208,8 @@ echo "---"
 
 mv ${PRECOMPFILE} ${SOURCEDIR}/${DESTDIR}/
 cd ${SOURCEDIR}
-if [ -n "${TARGET}" ]; then
-	mv ${DESTDIR}/${PRECOMPFILE} ${DESTDIR}/${TARGET}.i
-	echo "Created file ${DESTDIR}/${TARGET}.i"
-else
-	echo "Created file ${DESTDIR}/${PRECOMPFILE}"
-fi
+mv ${DESTDIR}/${PRECOMPFILE} ${DESTDIR}/${TARGET}
+echo "Created file ${DESTDIR}/${TARGET}"
 
 # Finally cleanup our mess
 cleanupWorkFiles
