bug 1651: added substitute options

diff --git a/CEP/LMWCommon/src/cexecms-part b/CEP/LMWCommon/src/cexecms-part
--- a/CEP/LMWCommon/src/cexecms-part
+++ b/CEP/LMWCommon/src/cexecms-part
@@ -1,34 +1,110 @@
 #!/bin/sh
 
 # The distributed part of cexecms.
-# It setups the environment and looks for files matching the given name.
-# It executes the given script for all files found.
+# It setups the environment and looks for files matching the given glob name.
+# It executes the given command for all files found.
 # It reports if no files are found.
+#
+# The following substitutions in the command will be made:
+#   <FILENAME> or <FN>  by the full file name
+#   <BASENAME> or <BN>  by the basename part
+#   <DIRNAME>  or <DN>  by the directory part
+# The first two can be followed by a . meaning that the extension is ignored.
+# If no substitutions are done, the command is executed like
+#     command filename arg1 arg2 ...
+# otherwise like
+#     command arg1 arg2...
 
-if test $# -le 3; then
-  echo 'run like:   rundistms envfile script msname [arg1 arg2 ...]'
-  echo '   where the SB-nr in the msname should be given as NNN'
-  exit 1
+showhelp()
+{
+  echo ' run like:   cexecms-part [-e envfile] command nameglob [arg1 arg2 ...]'
+  echo '     see cexecms for more information'
+}
+
+if test $# -lt 2; then
+    showhelp
+    exit 1
 fi
-envfile=$1
+# Get a possibly given envfile.
+envfile=
+if test "$1" = "-e"; then
+    shift
+    . $1
+    shift
+fi
+if test $# -lt 2; then
+    showhelp
+    exit 1
+fi
+command="$1"
 shift
-script=$1
-shift
-msname=$1
+nameglob="$1"
 shift
 
-# Setup the environment by sourcing the file.
-. $envfile
+# Setup the environment by sourcing the envfile.
+if test "$envfile" != ""; then
+    . $envfile
+fi
 
-name1=`echo "$msname" | sed 's/\(.*SB\)NNN.*/\1/'`
-name2=`echo "$msname" | sed 's/.*SBNNN\(.*\)/\1/'`
-names=`ls -d $name1[0-9][0-9][0-9]$name2 2>&1`
+# Find all matching files (first substitute # by [0-9]).
+nameg=`echo "$nameglob" | sed -e 's%#%[0-9]%g'`
+names=`ls -d $nameg 2>&1`
 if test $? != 0; then
-  echo "No file like $msname found"
-  exit 0
+    echo "No file matching $nameg found"
+    exit 0
 fi
 
-for name in $names
+# cexecms had to substitute special characters, so reverse it.
+command=`echo "$command" | sed \
+    -e 's%:SPACE:% %g' \
+    -e 's%:LT:%<%g' \
+    -e 's%:GT:%>%g' \
+    -e 's%:LPAR:%(%g' \
+    -e 's%:RPAR:%)%g' \
+    -e 's%:LBRACE:%{%g' \
+    -e 's%:RBRACE:%}%g' \
+    -e 's%:LBRACKET:%[%g' \
+    -e 's%:RBRACKET:%]%g' \
+    -e 's%:VBAR:%|%g' \
+    -e 's%:AMPERSAND:%\\&%g' \
+    -e 's%:ASTERIX:%*%g' \
+    -e 's%:NOT:%!%g' \
+    -e 's%:HASH:%#%g' \
+    -e 's%:TILDE:%~%g' \
+    -e 's%:COMMA:%,%g' \
+    -e 's%:QMARK:%?%g' \
+    -e 's%:SEMICOLON:%;%g' \
+    -e 's%:DQUOTE:%"%g' \
+    -e "s%:SQUOTE:%'%g" \
+    -e 's%:DOLLAR:%$%g'`
+
+# Process all files.
+# Substitute placeholders in the command.
+for fname in $names
 do
-  $script $name "$@"
+    dname=`dirname $fname`
+    bname=`basename $fname`
+    bnamed=`echo $bname | sed -e 's%\..*%%'`
+    fnamed=$dname/$bnamed
+    commandnew=`echo "$command" | sed \
+	-e "s%:FN:%$fname%g" \
+	-e "s%:DN:%$dname%g" \
+	-e "s%:BN:%$bname%g" \
+	-e "s%:FN\.:%$fnamed%g" \
+	-e "s%:DN\.:%$dnamed%g" \
+	-e "s%:BN\.:%$bnamed%g" \
+	-e "s%:FILENAME:%$fname%g" \
+	-e "s%:DIRNAME:%$dname%g" \
+	-e "s%:BASENAME:%$bname%g" \
+	-e "s%:FILENAME\.:%$fnamed%g" \
+	-e "s%:DIRNAME\.:%$dnamed%g" \
+	-e "s%:BASENAME\.:%$bnamed%g"`
+    # If nothing substituted, give the file name to the command.
+    # Use eval to execute the command, otherwise the shell gets confused
+    # by possible quoted parts.
+    if test "$commandnew" = "$command"; then
+	eval $command $fname "$@" || echo "Failure in $command $fname $*"
+    else
+	eval $commandnew "$@" || echo "Failure in $commandnew $*"
+    fi
 done
