Task #2699 Added options -i,-d,-w,-p to cexecms

diff --git a/CEP/LMWCommon/src/cexecms-part b/CEP/LMWCommon/src/cexecms-part
--- a/CEP/LMWCommon/src/cexecms-part
+++ b/CEP/LMWCommon/src/cexecms-part
@@ -18,23 +18,47 @@
 
 showhelp()
 {
-  echo ' run like:   cexecms-part [-e envfile] command nameglob [arg1 arg2 ...]'
+  echo ' run like:   cexecms-part [-d] [-e envfile] [-w workdir] [-p parset] command nameglob [arg1 arg2 ...]'
   echo '     see cexecms for more information'
 }
 
-if test $# -lt 2; then
-    showhelp
-    exit 1
-fi
-# Get a possibly given envfile.
+# Handle possible options.
 envfile=
-if test "$1" = "-e"; then
+parset=
+dryrun=0
+workdir=
+while [ $# != 0 ]
+do
+  if test "$1" = "-e"; then
     shift
-    . $1
+    envfile="$1"
     shift
-fi
-parset=$1
-shift
+  elif test "$1" = "-p"; then
+    shift
+    parset="$1"
+    shift
+  elif test "$1" = "-w"; then
+    shift
+    workdir="$1"
+    shift
+  elif test "$1" = "-d"; then
+    shift
+    dryrun=1
+  else
+    case "$1" in
+    -*)
+      echo "$1 is an unknown cexecms-part option"
+      exit 1
+      ;;
+    *)
+      # A command has been found, so stop parsing options.
+      break
+      ;;
+    esac
+  fi
+done
+
+# Test if at least 2 parameters.
 if test $# -lt 2; then
     showhelp
     exit 1
@@ -46,7 +70,11 @@ shift
 
 # Setup the environment by sourcing the envfile.
 if test "$envfile" != ""; then
-    . $envfile
+    . "$envfile"
+fi
+# cd if work directory is given.
+if test "$workdir" != ""; then
+    cd "$workdir"  ||  exit 1
 fi
 
 # Find all matching files (first substitute # by [0-9] and substitute special characters back).
@@ -96,10 +124,12 @@ command=`echo "$command" | sed \
 # Substitute placeholders in the command and possible parset.
 for fname in $names
 do
-    dname=`dirname $fname`
-    bname=`basename $fname`
-    bnamed=`echo $bname | sed -e 's%\..*%%'`
-    fnamed=$dname/$bnamed
+    # Form the various placeholder replacements.
+    dname=`dirname $fname`                          # directory
+    bname=`basename $fname`                         # basename
+    bnamed=`echo $bname | sed -e 's%\..*%%'`        # basename without extension
+    fnamed=$dname/$bnamed                           # full name without extension
+    # Replace the placeholders.
     commandnew=`echo "$command" | sed \
 	-e "s%<FN>%$fname%g" \
 	-e "s%<DN>%$dname%g" \
@@ -113,8 +143,8 @@ do
 	-e "s%<FILENAME\.>%$fnamed%g" \
 	-e "s%<DIRNAME\.>%$dnamed%g" \
 	-e "s%<BASENAME\.>%$bnamed%g"`
-    # If a parset is given, replace placeholders in there as well.
     if test "$parset" != ""; then
+        # A parset is given, replace placeholders in there as well.
         psname=$HOME/`basename $parset`-$USER-$$
         sed \
 	-e "s%<FN>%$fname%g" \
@@ -130,16 +160,30 @@ do
 	-e "s%<DIRNAME\.>%$dnamed%g" \
 	-e "s%<BASENAME\.>%$bnamed%g" \
         $parset > $psname
-	eval $commandnew $psname "$@" || echo "Failure in $commandnew $psname $*"
+	if test $dryrun = 1; then
+	    echo "Dryrun: " $commandnew $psname "$@"
+	    cat $psname
+        else
+	    eval $commandnew $psname "$@" || echo "Failure in $commandnew $psname $*"
+	fi
         rm -f $psname
     else
+        # Execute the command.
         # If nothing substituted, give the file name to the command.
         # Use eval to execute the command, otherwise the shell gets confused
         # by possible quoted parts.
         if test "$commandnew" = "$command"; then
-	    eval $command $fname "$@" || echo "Failure in $command $fname $*"
+	    if test $dryrun = 1; then
+		echo "Dryrun: " $command $fname "$@"
+	    else
+		eval $command $fname "$@" || echo "Failure in $command $fname $*"
+	    fi
         else
-	    eval $commandnew "$@" || echo "Failure in $commandnew $*"
-        fi
+	    if test $dryrun = 1; then
+		echo "$Dryrun " $commandnew "$@"
+	    else
+		eval $commandnew "$@" || echo "Failure in $commandnew $*"
+            fi
+	fi
     fi
 done
