%[ER:27]% Handles multiple classes in one .h file. Not tested yet but generated code looks good. R-layer does not work in this version. Early checkin to get a short feedback loop from the CEPFrame project.

diff --git a/LCS/databases/PL/scripts/genDBcode b/LCS/databases/PL/scripts/genDBcode
--- a/LCS/databases/PL/scripts/genDBcode
+++ b/LCS/databases/PL/scripts/genDBcode
@@ -28,7 +28,7 @@
 #
 # $Id$
 #
-VERSION="v2.4"
+VERSION="v2.5"
 DEBUGMODE=false
 
 #
@@ -42,7 +42,7 @@ RECaddBCA()
 	echo "// to the members of the ${Class} class."
 	echo "class ${Class}_BCA {"
 	echo "public:"
-	echo "	void operator()(BoundIOs& cols, ${Class}& rowbuf) {"
+	echo "	void operator()(dtl::BoundIOs& cols, ${Class}& rowbuf) {"
 	# get all 'basic' members of the class
 	grep ^$Class ${MAPWRKFILE} | grep "::" | while read line
 	do
@@ -175,9 +175,9 @@ TPOaddBCA()
 {
 	Class=$1
 	
-	echo "// vindCols() 'binds' the database columns represented by \a cols"
+	echo "// bindCols() 'binds' the database columns represented by a cols"
 	echo "// to the members of the DBRep<${Class}> class."
-	echo "void DBRep<${Class}>::bindCols(BoundIOs& cols) {"
+	echo "void DBRep<${Class}>::bindCols(dtl::BoundIOs& cols) {"
 
 	# add all 'basic' members of the class
 	grep ^$Class ${MAPWRKFILE} | grep "::" | while read line
@@ -336,21 +336,22 @@ initTmpfile()
 {
 	echo "#This temporarely file was generated by genDBcode"
 	echo "#It should have been cleaned up by genDBcode, please remove it"
-	echo "#ClassName:TableName:Ctype:MemberName:ColumnName:SubclassName:DBtype"
+	echo "#ClassName:TableName:Ctype:MemberName:ColumnName:SubclassName:DBtype:File"
 }
 
 #
-# initSrcfile filetype class
+# initSrcfile filetype filename
 #
 # Adds an informational header to the C++ source- of headerfile.
+# and includes the correct headerfiles.
 #
 initSrcfile()
 {
 	FileType=$1
-	Class=$2
+	File=$2
 
 	echo -n "//# This file was generated by genDBcode ${VERSION} on " ; date
-	echo "//# with the command: genDBcode ${MAPFILE} ${FUNFILE} ${LAYER} ${CLASS}"
+	echo "//# with the command: genDBcode ${LAYER} ${MAPFILE} ${FUNFILE} ${CLASS}"
 	echo -n "//# from the directory: " ; pwd
 	echo "//#"
 	echo "//# EDITING THIS FILE MANUALLY IS AT YOUR OWN RISK"
@@ -359,16 +360,36 @@ initSrcfile()
 
 	# include the headerfiles in the C++ sourcefile
 	if [ "${FileType}" == "cc" ]; then
-		echo "#include \"${FILEPREFIX}${Class}.h\""
-		# Grep all subclasses of this class and include those headerfiles also.
-		grep ^${Class} ${MAPWRKFILE} | grep -v "::" | while read line
+		# By combining the contents of the ClassLocationFile and the contents
+		# of the MapWrkfile we can figure out which files to include.
+		# First we look in the ClassLocation file which classes are defined
+		# in the given File ($2), next we check for these classes in which
+		# files their sub-classses are defined.
+
+		>${INCLUDEWRKFILE}							# clear the work file
+		# find the classes defined in the File ($2)
+		grep ":${File}.h" ${CLASSLOCATIONWRKFILE} | while read cl_line
 		do
-			subClass=`echo $line | cut -d':' -f6`
-			echo "#include \"${FILEPREFIX}${subClass}.h\""
+			Class=`echo $cl_line | cut -d":" -f1`
+			# find their subclasses
+			grep "^${Class}:" ${MAPWRKFILE} | grep -v "::" | while read m_line
+			do
+				SubClass=`echo $m_line | cut -d':' -f6`
+				# where is this sub class located? 
+				sl_line=`grep "${SubClass}:" ${CLASSLOCATIONWRKFILE}`
+				SubClassLocation=`echo $sl_line | cut -d":" -f2`
+				if [ "${SubClassLocation}" != "${File}.h" ]; then
+					echo "#include \"${FILEPREFIX}${SubClassLocation}\"" >>${INCLUDEWRKFILE}
+				fi
+			done
 		done
+		# Finally add the found files only once
+		cat ${INCLUDEWRKFILE} | sort | uniq -u
+		rm ${INCLUDEWRKFILE}						# cleanup the mess
+
+		# And include our own header file also ofcourse.
+		echo "#include \"${FILEPREFIX}${File}.h\""
 		echo "#include <PL/TPersistentObject.h>"
-		echo ""
-		echo "using namespace dtl;"
 		echo ""
 	else	# its a headerfile
 		TimeStamp=`date +%y%m%d%H%M%S`
@@ -377,8 +398,7 @@ initSrcfile()
 		echo "#if !defined(${FileLabel})"
 		echo "#define ${FileLabel}"
 		echo ""
-		File=`grep ^${Class} ${MAPWRKFILE} | head -1 | cut -d':' -f8`
-		echo "#include \"${File}\""
+		echo "#include \"${File}.h\""
 		echo "#include <PL/DBRep.h>"
 		echo ""
 	fi
@@ -406,7 +426,8 @@ closeHeaderfile()
 cleanupWorkFiles()
 {
 	if [ "${DEBUGMODE}" != "true" ]; then
-		rm -f ${MAPWRKFILE} ${ALLCLASSESWRKFILE}
+		rm -f ${MAPWRKFILE} ${ALLFILESWRKFILE} ${CLASSLOCATIONWRKFILE} \
+			  ${INCLUDEWRKFILE}
 	else
 		echo "DEBUGMODE, NOT REMOVING TEMPFILES IN /tmp"
 	fi
@@ -460,7 +481,9 @@ convertMapfile()
 			CurTable=$name
 			;;
 		File|file|FILE)					# File keyword
-			CurFile=$name
+			CurFile=$name				
+			# NOTE: we assume that File always comes after Class!!!
+			echo "${CurClass}:${CurFile}" >> ${CLASSLOCATIONWRKFILE}
 			;;
 		*)								# no keyword, assume fieldname
 			# label (=c_type) may be xxx::yyy, change it to xxx!yyy
@@ -499,77 +522,98 @@ hasSubClasses()
 	fi
 
 }
+
+# SyntaxError msg
+#
+# Shows the right syntax on stdout together with the given msg.
+# Exits afterwards.
+SyntaxError()
+{
+	Msg=$1
+
+	[ "X${Msg}" != "X" ] && echo "ERROR: ${Msg}"
+	echo "Syntax: $(basename $0) P mapfile [class]"
+	echo "or"
+	echo "Syntax: $(basename $0) R mapfile functionfile [class]"
+	exit 1
+}
+
 #------------------------------- MAIN program ---------------------------------
 #
-# Check invocation syntax: [-d destdir] genDBcode mapfile cmdfile layer [class]
+# Check invocation syntax: genDBcode [-d destdir] P mapfile [class]
+# Check invocation syntax: genDBcode [-d destdir] R mapfile funfile [class]
 #
 
 # Check option argument
-DESTDIR="./"						# assume no destination directory
+DESTDIR="."							# assume no destination directory
 eval set argv=`getopt "d:" $*`		# reformat arguments
 shift
 case "$1" in
 	-d)	DESTDIR=$2
-		if [ ! -d ${DESTDIR} ]; then
-			echo "Destination directory >${DESTDIR}< does not exist"
-			exit 1
-		fi
+		[ -d ${DESTDIR} ] || 
+				SyntaxError "Destination directory >${DESTDIR}< does not exist"
 		shift 2
 		;;
 esac
 shift								# remove --
 
+# Need at least two arguments
+[ $# -ge 2 ] || SyntaxError "Need at least the layer arguments and a mapfile."
+
+typeset -u LAYER=$1
+MAPFILE=$2
+
+# Check Layer type
+case "${LAYER}" in
+R)		FILEPREFIX="Rec"		;;
+P)		FILEPREFIX="PO_"		;;
+*)		SyntaxError "Layer should be R(ecord) or P(ersistency), not >${LAYER}<"
+esac
+
 # Check other arguments
 case $# in
-	3)	MAPFILE=$1					# genDBcode mapfile funfile layer
-		FUNFILE=$2
-		typeset -u LAYER=$3
-		GREPMASK=""
-		CLASS=""
+	2)	if [ "${LAYER}" == "R" ]; then		# only genDBcode P mapfile is allowed
+			SyntaxError "Wrong number of arguments"
+		fi
 		;;
-	4)	MAPFILE=$1					# genDBcode mapfile funfile layer classname
-		FUNFILE=$2
-		typeset -u LAYER=$3
-		GREPMASK=" | grep ^$4"
-		CLASS=$4
+	3)  if [ "${LAYER}" == "R" ]; then		# genDBcode R mapfile funfile
+			FUNFILE=$3
+			GREPMASK=""
+			CLASS=""
+		else								# genDBcode P mapfile class
+			FUNFILE=""
+			GREPMASK=" | grep ^$3"
+			CLASS=$3
+		fi
 		;;
-	*)	echo "Syntax: $0 mapfile functionfile layer [class]"
-		echo "        where layer is R(ecord) or P(ersistency)"
-		exit 0
+	4)  if [ "${LAYER}" == "R" ]; then		# genDBcode R mapfile funfile class
+			FUNFILE=$3
+			GREPMASK=" | grep ^$4"
+			CLASS=$4
+		else								# genDBcode P mapfile ???
+			SyntaxError "Too many arguments"
+		fi
+		;;
+	*)	SyntaxError "Wrong number of arguments"
 		;;
 esac
 
 # Mapfile must exist
-#
-if [ ! -s ${MAPFILE} ]; then
-	echo "File ${MAPFILE} doesn't exist\n"
-	exit 1
-fi
+[ -s ${MAPFILE} ] || SyntaxError "File ${MAPFILE} doesn't exist"
 
 # Functionfile must exist
-#
-if [ ! -s ${FUNFILE} ]; then
-	echo "File ${FUNFILE} doesn't exist\n"
-	exit 1
-fi
-
-# Check Layer type
-#
-case "${LAYER}" in
-R)		FILEPREFIX="Rec"		;;
-P)		FILEPREFIX="PO_"		;;
-*)		echo "Layer should be R(ecord) or P(ersistency), not >${LAYER}<\n"
-		exit 1
-esac
+[ "X${FUNFILE}" != "X" -a ! -s "${FUNFILE}" ] && 
+									SyntaxError "File ${FUNFILE} doesn't exist"
 
 # All arguments seem ok, continue processing
 
 # Initialize some variables
 #
 ROLLBACKCODE=false				# whether or not generate rollback code
-LCSBASEFILE=${DESTDIR}/LCS_base.h
 MAPWRKFILE=/tmp/mapinfo.LCS.$$
-ALLCLASSESWRKFILE=/tmp/created.LCS.$$
+ALLFILESWRKFILE=/tmp/created.LCS.$$
+CLASSLOCATIONWRKFILE=/tmp/classloc.LCS.$$
+INCLUDEWRKFILE=/tmp/include.LCS.$$
 
 # Make sure there are no old workfiles left
 cleanupWorkFiles
@@ -583,52 +627,30 @@ echo "Analysing mapfile"
 initTmpfile					> ${MAPWRKFILE}
 convertMapfile ${MAPFILE}	>>${MAPWRKFILE}
 
+# When generating the Record layer use the functionfile as primary input
 # Scan the functionfile to determine what code should be generated
-#
-PrevClass="Unknown"
-eval "cleanlist $FUNFILE $GREPMASK" | \
-while read class action clause
-do
-	# minimal check on layout of line
-	if [ -z "$class" -o -z "$action" ]; then
-		continue
-	fi
+if [ "${LAYER}" == "R" ]; then
+	PrevClass="Unknown"
+	eval "cleanlist $FUNFILE $GREPMASK" | \
+	while read class action clause
+	do
+		# minimal check on layout of line
+		if [ -z "$class" -o -z "$action" ]; then
+			continue
+		fi
 
-	# New class? generate the necc. structures in the new sourcefile.
-	# generate exacly one BCA for each class
-	if [ "${PrevClass}" != "${class}" ]; then
-		case ${LAYER} in
-		R) 	SOURCEFILE=${DESTDIR}/${FILEPREFIX}${class}.tcc
+		# New class? generate the necc. structures in the new sourcefile.
+		# generate exacly one BCA for each class
+		if [ "${PrevClass}" != "${class}" ]; then
+			SOURCEFILE=${DESTDIR}/${FILEPREFIX}${class}.tcc
 			HEADERFILE=${DESTDIR}/${FILEPREFIX}${class}.h
 			initSrcfile "cc" ${class}  > ${SOURCEFILE}
 			RECaddBCA 	     ${class}  >>${SOURCEFILE}
-			;;
-		P) 	# start a new headerfile and sourcefile
-			SOURCEFILE=${DESTDIR}/${FILEPREFIX}${class}.tcc
-			HEADERFILE=${DESTDIR}/${FILEPREFIX}${class}.h
-			echo ${class}	 							>>${ALLCLASSESWRKFILE}
-			echo "Creating code for class ${class}"
-			initSrcfile "cc"				${class} 	> ${SOURCEFILE}
-			TPOopenNamespace							>>${SOURCEFILE}
-			TPOaddBCA 						${class} 	>>${SOURCEFILE}
-			TPOaddToDatabaseRep				${class} 	>>${SOURCEFILE} 
-			TPOaddFromDatabaseRep			${class} 	>>${SOURCEFILE} 
-			TPOaddInitRoutine				${class} 	>>${SOURCEFILE} 
-			TPOaddAttributemap				${class} 	>>${SOURCEFILE} 
-			initSrcfile "h"					${class} 	> ${HEADERFILE}
-			TPOopenNamespace							>>${HEADERFILE}
-			TPOaddDTLstruct					${class} 	>>${HEADERFILE}
-			TPOcloseNamespace							>>${HEADERFILE}
-			closeHeaderfile					${class}	>>${HEADERFILE}
-			;;
-		esac
-		PrevClass=${class}
-	fi
+			PrevClass=${class}
+		fi
 
-	# dispatch the action
-	typeset -u action=${action}						# to uppercase
-	case ${LAYER} in
-	R)
+		# dispatch the action
+		typeset -u action=${action}						# to uppercase
 		case $action in
 		I) RECaddInsertRoutine $class 			>>${SOURCEFILE}		;;
 		U) RECaddUpdateRoutine $class "$clause"	>>${SOURCEFILE}		;;
@@ -637,15 +659,56 @@ do
 		*) echo "ERROR:Unknown function >$action< for class >$class< in file >$FUNFILE<"
 		   ;;
 		esac
-		;;
-	esac
-done
+	done
+fi	# Record layer
 
-# Finish all created .tcc files
+# When generating the Persistence layer use the mapfile as primairy input
 if [ "${LAYER}" == "P" ]; then
-	cat ${ALLCLASSESWRKFILE} | while read Class
+	PrevClass="Unknown"
+	PrevFile="Unknown"
+	eval "cleanlist $MAPWRKFILE $GREPMASK" | \
+	while read line
 	do
-		TPOcloseNamespace >>${DESTDIR}/${FILEPREFIX}${Class}.tcc
+		# Where is this line about?
+		Class=`echo $line | cut -d':' -f1`
+		File=`echo $line | cut -d':' -f8 | sed "s/\.h$//"`
+		
+		if [ "${PrevFile}" != "${File}" ]; then
+			SOURCEFILE=${DESTDIR}/${FILEPREFIX}${File}.tcc
+			HEADERFILE=${DESTDIR}/${FILEPREFIX}${File}.h
+
+			# Brand new file or already created?
+			grep ${File} ${ALLFILESWRKFILE} >/dev/null 2>&1
+			if [ $? -ne 0 ]; then
+				initSrcfile "cc"			${File} 	> ${SOURCEFILE}
+				TPOopenNamespace						>>${SOURCEFILE}
+				initSrcfile "h"				${File} 	> ${HEADERFILE}
+				TPOopenNamespace						>>${HEADERFILE}
+				echo ${File} 							>>${ALLFILESWRKFILE}
+			fi
+			PrevFile=${File}
+		fi
+	
+		if [ "${PrevClass}" != "${Class}" ]; then
+			echo "Creating code for class ${Class}"
+			TPOaddBCA 						${Class} 	>>${SOURCEFILE}
+			TPOaddToDatabaseRep				${Class} 	>>${SOURCEFILE} 
+			TPOaddFromDatabaseRep			${Class} 	>>${SOURCEFILE} 
+			TPOaddInitRoutine				${Class} 	>>${SOURCEFILE} 
+			TPOaddAttributemap				${Class} 	>>${SOURCEFILE} 
+			TPOaddDTLstruct					${Class} 	>>${HEADERFILE}
+			PrevClass=${Class}
+		fi
+	done
+
+	# Finish all created .tcc files
+	cat ${ALLFILESWRKFILE} | while read File
+	do
+		SOURCEFILE=${DESTDIR}/${FILEPREFIX}${File}.tcc
+		HEADERFILE=${DESTDIR}/${FILEPREFIX}${File}.h
+		TPOcloseNamespace			>>${HEADERFILE}
+		closeHeaderfile		${File}	>>${HEADERFILE}
+		TPOcloseNamespace 			>>${SOURCEFILE}
 	done
 fi
 
