Task #8437: Fixed calls to docker-template and versiondocker

diff --git a/branches/LOFAR-Task8437/Docker/docker-template b/branches/LOFAR-Task8437/Docker/docker-template
--- a/branches/LOFAR-Task8437/Docker/docker-template
+++ b/branches/LOFAR-Task8437/Docker/docker-template
@@ -18,9 +18,34 @@
 # ----- LOFAR_BRANCH_NAME = tags/LOFAR-Release-2_15_1 -----
 # ----- LOFAR_BRANCH_NAME = UNKNOWN -----
 
+function usage() {
+  echo "$0 [-v VERSIONDOCKER]"
+  echo ""
+  echo "  -v VERSIONDOCKER   Provides location of 'versiondocker' executable"
+  echo ""
+  exit 1
+}
+
+# Defaults
+VERSION_DOCKER="versiondocker"
+
+# Parse options
+while getopts "hv:" opt; do
+  case $opt in
+    h)  usage
+        ;;
+    v)  VERSION_DOCKER="$OPTARG"
+        ;;
+    \?) error "Invalid option: -$OPTARG"
+        ;;
+    :)  error "Option requires an argument: -$OPTARG"
+        ;;
+  esac
+done
+[ $OPTIND -eq 1 ] && usage
+
 # Make sure we obtain info about the project source!
-#PATH=$PATH:.
-VERSION_INFO=`(versiondocker || ./versiondocker) 2>/dev/null` # in cmake, executable is in .
+VERSION_INFO=`$VERSION_DOCKER`
 
 # Extract branch name w.r.t. repository root, e.g. branches/LOFAR-Task1234
 export LOFAR_BRANCH_NAME=`echo "$VERSION_INFO" | perl -ne 'print "$1" if /branch += +(.+)/;'`
