Task #7347 #7350: Cobalt: Communicate status and feedback using qpid

diff --git a/branches/LOFAR-Task7336/SubSystems/Online_Cobalt/test/runtest.sh.in b/branches/LOFAR-Task7336/SubSystems/Online_Cobalt/test/runtest.sh.in
--- a/branches/LOFAR-Task7336/SubSystems/Online_Cobalt/test/runtest.sh.in
+++ b/branches/LOFAR-Task7336/SubSystems/Online_Cobalt/test/runtest.sh.in
@@ -36,7 +36,7 @@ echo "  in directory $(pwd)"
   [ -n "$(echo *.raw)" ]  || error "runObservation.sh produced no output files"
 
   # create script to accept output (ie. copy it to the source dir for check in)
-  echo "#!/bin/sh
+  echo "#!/bin/bash
   cp ${PWD}/*.raw ${REFDIR}" > accept_output
   chmod a+x accept_output
 
@@ -60,5 +60,16 @@ echo "  in directory $(pwd)"
     done
   done
 
+  if [ $HAVE_QPID == "TRUE" ]; then
+    # validate the contents of the queues
+    mkdir "queues" || error "Failed to create temporary directory ${OUTDIR}/queues"
+    echo "[ -d ${PWD}/queues ] && cp -r ${PWD}/queues ${REFDIR}" >> accept_output
+    QUEUES=`cd ${REFDIR}/queues 2>/dev/null && ls`
+    for Q in $QUEUES; do
+      echo "Comparing output of queue $Q"
+      @QPID_RECEIVE_EXECUTABLE@ -b 127.0.0.1 -a $Q --ignore-reply-to > queues/$Q || error "Could not read output of queue $Q"
+      diff ${REFDIR}/queues/$Q queues/$Q || error "Output of queue $Q does not match"
+    done
+  fi
 ) || exit 1
 
