Change marker string from %%%%%% to :::::: since % is a character with a special meaning in crontab.

diff --git a/trunk/Makefile b/trunk/Makefile
--- a/trunk/Makefile
+++ b/trunk/Makefile
@@ -68,10 +68,10 @@ MAKE_OPTIONS = -j2
 all: start bootstrap $(VARIANTS) check stop
 
 start:
-	@echo && echo "%%%%%% BUILD START" && echo
+	@echo && echo ":::::: BUILD START" && echo
 
 stop:
-	@echo && echo "%%%%%% BUILD COMPLETE" && echo
+	@echo && echo ":::::: BUILD COMPLETE" && echo
 
 #
 # check target: check all variants that have been specified in the
@@ -85,12 +85,12 @@ check: $(VARIANTS:.variant=.variant_check)
 bootstrap:
 	@for d in $(PACKAGES); do \
 		( echo \
-		&& echo "%%%%%% BOOTSTRAPPING $$d" \
+		&& echo ":::::: BOOTSTRAPPING $$d" \
 		&& echo \
 		&& ( ( cd $$d && ./bootstrap && ./bootstrap ) \
-			|| echo "%%%%%% ERROR" ) \
+			|| echo ":::::: ERROR" ) \
 		&& echo \
-		&& echo "%%%%%% DONE BOOTSTRAPPING $$d" \
+		&& echo ":::::: DONE BOOTSTRAPPING $$d" \
 		&& echo ) ; \
 	done
 
@@ -109,9 +109,9 @@ bootstrap:
 	variant_make_options=$($@.make); \
 	for d in $(PACKAGES); do \
 		( echo \
-		&& echo "%%%%%% BUILDING VARIANT $$variant FOR PACKAGE $$d" \
-		&& echo "%%%%%% variant_conf_options = $$variant_conf_options" \
-		&& echo "%%%%%% variant_make_options = $$variant_make_options" \
+		&& echo ":::::: BUILDING VARIANT $$variant FOR PACKAGE $$d" \
+		&& echo ":::::: variant_conf_options = $$variant_conf_options" \
+		&& echo ":::::: variant_make_options = $$variant_make_options" \
 		&& echo \
 		&& date \
 		&& $(RM) -rf $$d/build/$$variant \
@@ -119,9 +119,9 @@ bootstrap:
 		&& cd $$d/build/$$variant \
 		&& ../../configure $$variant_conf_options \
 		&& (make -k $(MAKE_OPTIONS) $$variant_make_options \
-			|| echo "%%%%%% ERROR" )) \
+			|| echo ":::::: ERROR" )) \
 		&& echo \
-		&& echo "%%%%%% FINISHED BUILDING VARIANT $$variant FOR PACKAGE $$d" \
+		&& echo ":::::: FINISHED BUILDING VARIANT $$variant FOR PACKAGE $$d" \
 		&& echo ; \
 	done; \
 	date
@@ -137,16 +137,16 @@ bootstrap:
 	variant_make_options=$($@.make); \
 	for d in $(PACKAGES); do \
 		( echo \
-		&& echo "%%%%%% CHECKING VARIANT $$variant FOR PACKAGE $$d" \
-		&& echo "%%%%%% variant_conf_options = $$variant_conf_options" \
-		&& echo "%%%%%% variant_make_options = $$variant_make_options" \
+		&& echo ":::::: CHECKING VARIANT $$variant FOR PACKAGE $$d" \
+		&& echo ":::::: variant_conf_options = $$variant_conf_options" \
+		&& echo ":::::: variant_make_options = $$variant_make_options" \
 		&& echo \
 		&& date \
 		&& cd $$d/build/$$variant \
 		&& (make -k $(MAKE_OPTIONS) $$variant_make_options check \
-			|| echo "%%%%%% ERROR" )) \
+			|| echo ":::::: ERROR" )) \
 		&& echo \
-		&& echo "%%%%%% FINISHED CHECKING VARIANT $$variant FOR PACKAGE $$d" \
+		&& echo ":::::: FINISHED CHECKING VARIANT $$variant FOR PACKAGE $$d" \
 		&& echo ; \
 	done; \
 	date
