%[ER: w]% Update for the creationg of the recordlayer.

diff --git a/trunk/LCS/databases/PLGEN/src/genDBcode b/trunk/LCS/databases/PLGEN/src/genDBcode
--- a/trunk/LCS/databases/PLGEN/src/genDBcode
+++ b/trunk/LCS/databases/PLGEN/src/genDBcode
@@ -30,7 +30,7 @@
 #
 # $Id$
 #
-VERSION="v2.6"
+VERSION="v2.7"
 DEBUGMODE=false
 
 #
@@ -57,17 +57,18 @@ RECaddBCA()
 }
 
 #
-# RECaddInsertRoutine class 
+# RECaddInsertRoutine class functionname
 #
 RECaddInsertRoutine()
 {
 	Class=$1
+	FunctName=$2
 	Table=`grep ^$Class ${MAPWRKFILE} | head -1 | cut -d"!" -f2`
 
 	echo "//"
 	echo "// Routine for insert this ${Class} object in the database."
 	echo "//"
-	echo "void insert_${Class}(${Class}&	insRec) {"
+	echo "void ${FunctName}(${Class}&	insRec) {"
 	echo "	DBView<${Class}>	insView(\"${Table}\", ${Class}_BCA());"
 	echo "	DBView<${Class}>::insert_iterator	insIter = insView;\n"
 
@@ -76,40 +77,50 @@ RECaddInsertRoutine()
 }
 
 #
-# RECaddDeleteRoutine class 
+# RECaddDeleteRoutine class functionname clause
 #
 RECaddDeleteRoutine()
 {
 	Class=$1
+	FunctName=$2
+	Clause=`echo $3 | cut -d"#" -f1`
 	Table=`grep ^$Class ${MAPWRKFILE} | head -1 | cut -d"!" -f2`
 
 	echo "//"
 	echo "// Routine for deleting this ${Class} object from the database."
 	echo "//"
-	echo "void delete_${Class}(${Class}&	delRec) {"
+	echo "void ${FunctName}(${Class}&	delRec) {"
 	echo "	DBView<${Class}>	delView(\"${Table}\", ${Class}_BCA());"
 	echo "	DBView<${Class}>::delete_iterator	delIter = delView;\n"
 	echo "	${Class}		delCondition;"
 	echo ""
-	echo "	delCondition = ...;"
+	echo "	delCondition = @@@;"
 	echo ""
 	echo "	*delIter = delCondition;"
 	echo "}\n"
 }
 
 #
-# RECaddSearchRoutine class clause
+# RECaddSearchRoutine class functionname clause
 #
 RECaddSearchRoutine()
 {
 	Class=$1
-	Clause=$2
+	FunctName=$2
+	Clause=`echo $3 | cut -d"#" -f1`
 	Table=`grep ^$Class ${MAPWRKFILE} | head -1 | cut -d"!" -f2`
 
-	echo "vector<${Class}> read_${Class}() {"
-	echo "	vector<${Class}> 		results;"
-	echo "	DBView<${Class}>			view(\"${Table}\", ${Class}_BCA(),"
-	echo "								\"${Clause}\");"
+	if [ ${#Clause} == 0 ]; then
+		echo "vector<${Class}> ${FunctName}(string whereClause) {"
+		echo "	vector<${Class}> 		results;"
+		echo "	DBView<${Class}>			view(\"${Table}\", ${Class}_BCA(),"
+		echo "								whereClause);"
+	else
+		echo "vector<${Class}> ${FunctName}() {"
+		echo "	vector<${Class}> 		results;"
+		echo "	DBView<${Class}>			view(\"${Table}\", ${Class}_BCA(),"
+		echo "								\"${Clause}\");"
+	fi
 	echo "	DBView<${Class}>::select_iterator	readIter = view.begin();\n"
 	echo "	for ( ; readIter != view.end(); ++readIter) {"
 	echo "		results.push_back(*readIter);"
@@ -119,20 +130,27 @@ RECaddSearchRoutine()
 }
 
 #
-# RECaddUpdateRoutine class clause
+# RECaddUpdateRoutine class functionname clause
 #
 RECaddUpdateRoutine()
 {
 	Class=$1
-	Clause=$2
+	FunctName=$2
+	Clause=`echo $3 | cut -d"#" -f1`
 	Table=`grep ^$Class ${MAPWRKFILE} | head -1 | cut -d"!" -f2`
 
 	echo "//"
 	echo "// Routine for updating this ${Class} object in the database."
 	echo "//"
-	echo "void update_${Class}(${Class}&	theRecord) {"
-	echo "	DBView<${Class}>			view(\"${Table}\", ${Class}_BCA(),"
-	echo "								\"${Clause}\");"
+	if [ ${#Clause} == 0 ]; then
+		echo "void ${FunctName}(${Class}&	theRecord, string whereClause) {"
+		echo "	DBView<${Class}>			view(\"${Table}\", ${Class}_BCA(),"
+		echo "								whereClause);"
+	else
+		echo "void ${FunctName}(${Class}&	theRecord) {"
+		echo "	DBView<${Class}>			view(\"${Table}\", ${Class}_BCA(),"
+		echo "								\"${Clause}\");"
+	fi
 	echo "	DBView<${Class}>::update_iterator	updIter = view;"
 	echo ""
 	echo "	// update the database"
@@ -287,9 +305,9 @@ TPOaddInitRoutine()
 	grep ^$Class ${MAPWRKFILE} | grep -v "!!" | while read line
 	do
 		Table=`echo $line | cut -d'!' -f2`
+		RelClass=`echo $line | cut -d'!' -f3`
 		Member=`echo $line | cut -d'!' -f4`
 		Relation=`echo $line | cut -d'!' -f6`
-		RelClass=`echo $line | cut -d'!' -f7`
 
 		echo "	{"
 		echo "	// create new TPersistentObject for ${Relation} ${RelClass}"
@@ -381,9 +399,9 @@ initSrcfile()
 	File=$2
 
 	echo -n "//# This file was generated by genDBcode ${VERSION} on " ; date
-	echo "//# with the command: genDBcode ${LAYER} ${MAPFILE} ${FUNFILE} ${CLASS}"
+	echo "//# with the command: ${COMMAND} ${LAYER} ${MAPFILE} ${FUNFILE} ${CLASS}"
 	echo -n "//# from the directory: " ; pwd
-	[ "${UseSumbNames}" != "true" ] && 
+	[ "${UseSymbNames}" != "true" ] && 
 		echo "//# The code does NOT use the symbolic names from the mapfile."
 	echo "//#"
 	echo "//# EDITING THIS FILE MANUALLY IS AT YOUR OWN RISK"
@@ -392,6 +410,12 @@ initSrcfile()
 
 	# include the headerfiles in the C++ sourcefile
 	if [ "${FileType}" == "cc" ]; then
+		if [ "${LAYER}" == "R" ]; then
+			echo "#include <dtl/DTL.h>"
+			echo ""
+			return
+		fi
+
 		# By combining the contents of the ClassLocationFile and the contents
 		# of the MapWrkfile we can figure out which files to include.
 		# First we look in the ClassLocation file which classes are defined
@@ -546,11 +570,12 @@ SyntaxError()
 {
 	Msg=$1
 
-	[ "X${Msg}" != "X" ] && echo "ERROR: ${Msg}"
+	[ -z "${Msg}" ] || echo "ERROR: ${Msg}"
 	echo "Syntax: $(basename $0) [-d destdir] [-S] P mapfile [class]"
 	echo "or"
 	echo "Syntax: $(basename $0) [-d destdir] [-S] R mapfile functionfile [class]"
-	echo "  -S	Do NOT use symbolic names in the generated code."
+	echo "  -S	Do *NOT* use symbolic names in the generated code."
+	echo ""
 	exit 1
 }
 
@@ -564,6 +589,7 @@ SyntaxError()
 DESTDIR="."							# assume no destination directory
 SYMBNAMEFLD=5						# assume use of symbolic names
 UseSymbNames=true
+COMMAND=$(basename $0)
 eval set argv=`getopt "d:S" $*`		# reformat arguments
 shift
 while [ "$1" != "--" ]
@@ -573,11 +599,13 @@ do
 			[ -d ${DESTDIR} ] || 
 					SyntaxError "Destination directory >${DESTDIR}< does not exist"
 			shift 2
+			COMMAND="${COMMAND} -d ${DESTDIR}"
 			;;
 		-S)	SYMBNAMEFLD=4
-			UseSymbNames=true
+			UseSymbNames=false
 			echo "Generated code does NOT using symbolic names"
 			shift 1
+			COMMAND="${COMMAND} -S"
 			;;
 	esac
 done
@@ -591,8 +619,10 @@ MAPFILE=$2
 
 # Check Layer type
 case "${LAYER}" in
-R)		FILEPREFIX="Rec"		;;
-P)		FILEPREFIX="PO_"		;;
+R)		FILEPREFIX="Rec"
+		FILEPOSTFIX="cc"		;;
+P)		FILEPREFIX="PO_"
+		FILEPOSTFIX="tcc"		;;
 *)		SyntaxError "Layer should be R(ecord) or P(ersistency), not >${LAYER}<"
 esac
 
@@ -652,90 +682,76 @@ echo "Analysing mapfile"
 initTmpfile					> ${MAPWRKFILE}
 convertMapfile ${MAPFILE}	>>${MAPWRKFILE}
 
-# When generating the Record layer use the functionfile as primary input
-# Scan the functionfile to determine what code should be generated
-if [ "${LAYER}" == "R" ]; then
-	PrevClass="Unknown"
-	eval "cleanlist $FUNFILE $GREPMASK" | \
-	while read class action clause
-	do
-		# minimal check on layout of line
-		if [ -z "$class" -o -z "$action" ]; then
-			continue
-		fi
-
-		# New class? generate the necc. structures in the new sourcefile.
-		# generate exacly one BCA for each class
-		if [ "${PrevClass}" != "${class}" ]; then
-			SOURCEFILE=${DESTDIR}/${FILEPREFIX}${class}.tcc
-			HEADERFILE=${DESTDIR}/${FILEPREFIX}${class}.h
-			initSrcfile "cc" ${class}  > ${SOURCEFILE}
-			RECaddBCA 	     ${class}  >>${SOURCEFILE}
-			PrevClass=${class}
-		fi
-
-		# dispatch the action
-		typeset -u action=${action}						# to uppercase
-		case $action in
-		I) RECaddInsertRoutine $class 			>>${SOURCEFILE}		;;
-		U) RECaddUpdateRoutine $class "$clause"	>>${SOURCEFILE}		;;
-		D) RECaddDeleteRoutine $class "$clause"	>>${SOURCEFILE}		;;
-		S) RECaddSearchRoutine $class "$clause"	>>${SOURCEFILE}		;;
-		*) echo "ERROR:Unknown function >$action< for class >$class< in file >$FUNFILE<"
-		   ;;
-		esac
-	done
-fi	# Record layer
-
-# When generating the Persistence layer use the mapfile as primairy input
-if [ "${LAYER}" == "P" ]; then
-	PrevClass="Unknown"
-	PrevFile="Unknown"
-	eval "cleanlist $MAPWRKFILE $GREPMASK" | \
-	while read line
-	do
-		# Where is this line about?
-		Class=`echo $line | cut -d'!' -f1`
-		File=`echo $line | cut -d'!' -f9 | sed "s/\.h$//"`
-		
-		if [ "${PrevFile}" != "${File}" ]; then
-			SOURCEFILE=${DESTDIR}/${FILEPREFIX}${File}.tcc
-			HEADERFILE=${DESTDIR}/${FILEPREFIX}${File}.h
-
-			# Brand new file or already created?
-			grep ${File} ${ALLFILESWRKFILE} >/dev/null 2>&1
-			if [ $? -ne 0 ]; then
-				initSrcfile "cc"			${File} 	> ${SOURCEFILE}
-				TPOopenNamespace						>>${SOURCEFILE}
-				initSrcfile "h"				${File} 	> ${HEADERFILE}
-				TPOopenNamespace						>>${HEADERFILE}
-				echo ${File} 							>>${ALLFILESWRKFILE}
-			fi
-			PrevFile=${File}
-		fi
+# We use the mapfile as primairy input
+PrevClass="Unknown"
+PrevFile="Unknown"
+eval "cleanlist $MAPWRKFILE $GREPMASK" | \
+while read line
+do
+	# Where is this line about?
+	Class=`echo $line | cut -d'!' -f1`
+	File=`echo $line | cut -d'!' -f9 | sed "s/\.h$//"`
 	
-		if [ "${PrevClass}" != "${Class}" ]; then
-			echo "Creating code for class ${Class}"
-			TPOaddBCA 						${Class} 	>>${SOURCEFILE}
+	if [ "${PrevFile}" != "${File}" ]; then
+		SOURCEFILE=${DESTDIR}/${FILEPREFIX}${File}.${FILEPOSTFIX}
+		HEADERFILE=${DESTDIR}/${FILEPREFIX}${File}.h
+
+		# Brand new file or already created?
+		grep ${File} ${ALLFILESWRKFILE} >/dev/null 2>&1
+		if [ $? -ne 0 ]; then
+			initSrcfile "cc"		${File}		> ${SOURCEFILE}
+			TPOopenNamespace					>>${SOURCEFILE}
+			if [ "${LAYER}" == "P" ]; then
+				initSrcfile "h"		${File} 	> ${HEADERFILE}
+				TPOopenNamespace				>>${HEADERFILE}
+			fi
+			echo ${File}						>>${ALLFILESWRKFILE}
+		fi
+		PrevFile=${File}
+	fi
+
+	if [ "${PrevClass}" != "${Class}" ]; then
+		echo "Creating code for class ${Class}"
+		case ${LAYER} in
+		R)	RECaddBCA 				${Class}	>>${SOURCEFILE}
+			eval "grep \"^"${Class}"\" $FUNFILE $GREPMASK" | \
+			while read class action functname clause
+			do
+				# dispatch the action
+				typeset -u action=${action}						# to uppercase
+				case $action in
+				I) RECaddInsertRoutine $class $functname 			>>${SOURCEFILE}	;;
+				U) RECaddUpdateRoutine $class $functname "$clause"	>>${SOURCEFILE}	;;
+				D) RECaddDeleteRoutine $class $functname "$clause"	>>${SOURCEFILE}	;;
+				S) RECaddSearchRoutine $class $functname "$clause"	>>${SOURCEFILE}	;;
+				*) echo "ERROR:Unknown function >$action< for class >$class< in file >$FUNFILE<"
+				   ;;
+				esac
+			done
+			;;
+		P)	TPOaddBCA 						${Class} 	>>${SOURCEFILE}
 			TPOaddToDatabaseRep				${Class} 	>>${SOURCEFILE} 
 			TPOaddFromDatabaseRep			${Class} 	>>${SOURCEFILE} 
 			TPOaddInitRoutine				${Class} 	>>${SOURCEFILE} 
 			TPOaddAttributemap				${Class} 	>>${SOURCEFILE} 
 			TPOaddDTLstruct					${Class} 	>>${HEADERFILE}
-			PrevClass=${Class}
-		fi
-	done
+			;;
+		esac
+		PrevClass=${Class}
+	fi
+done
 
-	# Finish all created .tcc files
-	cat ${ALLFILESWRKFILE} | while read File
-	do
-		SOURCEFILE=${DESTDIR}/${FILEPREFIX}${File}.tcc
-		HEADERFILE=${DESTDIR}/${FILEPREFIX}${File}.h
+# Finish all created .tcc files
+cat ${ALLFILESWRKFILE} | while read File
+do
+	SOURCEFILE=${DESTDIR}/${FILEPREFIX}${File}.${FILEPOSTFIX}
+	HEADERFILE=${DESTDIR}/${FILEPREFIX}${File}.h
+	if [ "${LAYER}" == "P" ]; then
 		TPOcloseNamespace			>>${HEADERFILE}
 		closeHeaderfile		${File}	>>${HEADERFILE}
-		TPOcloseNamespace 			>>${SOURCEFILE}
-	done
-fi
+	fi
+	TPOcloseNamespace 			>>${SOURCEFILE}
+done
 
 # Finally cleanup our mess
 cleanupWorkFiles
