BugID: 925 Added support of remote builds Added support of build in separate build tree

diff --git a/autoconf_share/rub b/autoconf_share/rub
--- a/autoconf_share/rub
+++ b/autoconf_share/rub
@@ -33,7 +33,7 @@
 # Furthermore it generates a lofarconf.in.private file which makes it possible
 # to bootstrap, configure and build all those packages (in the correct order).
 #
-# The command has to be run from the LOFAR directory in the user's tree.
+# The command has to be run from the LOFAR source directory in the user's tree.
 
 
 # Find the path used to start the script.
@@ -65,9 +65,11 @@ cvsdefault=cvs
 cvscomm=$cvsdefault
 updq=
 cvstag=
+kopt=
 jobsopt=
 variants=
 buildmake=1
+boot=2
 conf=0
 confopt=
 clean=0
@@ -131,6 +133,15 @@ do
   elif [ "$1" = -nor ]; then
     shift
     cvstag=
+  # continue after error?
+  elif [ "$1" = -k ]; then
+    shift
+    kopt='-k'
+    shift
+  elif [ "$1" = -nok ]; then
+    shift
+    kopt=
+    shift
   # parallel make option?
   elif [ "$1" = -j ]; then
     shift
@@ -168,6 +179,12 @@ do
   elif [ "$1" = -nomake ]; then
     shift
     buildmake=0
+  elif [ "$1" = -boot ]; then
+    shift
+    boot=1
+  elif [ "$1" = -noboot ]; then
+    shift
+    boot=0
   elif [ "$1" = -conf ]; then
     shift
     conf=1
@@ -210,7 +227,7 @@ do
     shift
     checktool="$1"
     shift
-  elif [ "$1" = -nocheck ]; then
+  elif [ "$1" = -nochecktool ]; then
     shift
     checktool=
   elif [ "$1" = -install ]; then
@@ -288,6 +305,9 @@ if [ $distclean = 1 ]; then
   clean=2
   conf=1
 fi
+if [ $boot = 2 -a $conf = 1 ]; then
+  boot=1
+fi
 
 if [ $help = 1 ]; then
   echo ''
@@ -296,13 +316,15 @@ if [ $help = 1 ]; then
   echo 'It uses the .spec.in or configure.in files to find out if specific'
   echo 'package versions are to be used.'
   echo 'If -build is given, the packages are configured, cleaned, built,'
-  echo ' checked, installed, distchecked, and/or rpm-ed for the given variant(s).'
+  echo ' checked, installed, distchecked, and/or rpm-ed for the given variant(s)'
+  echo 'using the script rubbuild.'
   echo ''
   echo 'Run as:'
   echo ' rub [-cvs cvs-command] [-update] [-updq string] [-r<cvstag>]'
-  echo '     [-recur[sive]] [-release=option] [-build variants]]'
-  echo '     [-system] [-conf] [-confopt string] [-j<option>] [-skipbuilt]'
-  echo '     [-[dist]clean] [-make] [-check] [-install] [-distcheck] [-rpm]'
+  echo '     [-recur[sive]] [-release=option] [-build variants]] [-skipbuilt]'
+  echo '     [-system] [-boot] [-conf] [-confopt string] [-k] [-j<option>]'
+  echo '     [-[dist]clean] [-make] [-check] [-checktool tool] [-install]'
+  echo '     [-distcheck] [-rpm]'
   echo '     package1 [-v<version>] [...]'
   echo ''
   echo '  -cvs cvs-command  is an optional cvs command making it possible to'
@@ -330,17 +352,15 @@ if [ $help = 1 ]; then
   echo '                    latest  Use latest package release version in CVS.'
   echo '                    main    Always use the MAIN for all packages.'
   echo '                    Default = -release=max.'
-  echo '  -build variants   gives the variants to do (e.g. gnu3_debug)'
-  echo '                    Separate multiple variants by whitespace and'
-  echo '                    enclose in quotes.'
-  echo '                    -build implies -make.'
-  echo '  -system           Do system build for given variants (using buildsys).'
-  echo '                    Options like -make, -conf, etc. are ignored.'
-  echo '                    Default is -nosystem.'
-  echo '  -conf             do bootstrap and configure before build.'
-  echo '                    Default is -noconf.'
-  echo '  -confopt string   configure options.'
-  echo '  -j<option>        Option for a parallel make. Default is -noj.'
+  echo '  -build variants   one or more variants to be built (e.g. "gnu_debug gnu_opt")'
+  echo '                    By default the build is done in the build subdirectory'
+  echo '                    of the source tree (e.g. in LCS/Common/build/gnu_opt).'
+  echo '                    A variant can be followed by :user@host to do a build'
+  echo '                    on another machine (using ssh). Rub does not wait'
+  echo '                    for such a build to complete'.
+  echo '                    A third part is :buildroot indicating a separate build tree'
+  echo '                    rooting in buildroot. /build is added if not present. E.g.'
+  echo '                    gnu_opt::/adir builds in /adir/build/gnu_opt/LCS/Common).'
   echo '  -skipbuilt        Skip packages built in the previous build run to'
   echo '                    speed up the build process (especially with -conf).'
   echo '                    It can be used after an unsuccesful built to start'
@@ -354,6 +374,17 @@ if [ $help = 1 ]; then
   echo '                    Default is -noskipbuilt'.
   echo '                    Note that it is not checked if source files have'
   echo '                    changed, so it should be used with care.'
+  echo '  -system           Do system build for given variants (using buildsys).'
+  echo '                    Options like -make, -conf, etc. are ignored. Implies -k.'
+  echo '                    Default is -nosystem.'
+  echo '  -boot             do bootstrap before build.'
+  echo '                    Default is -boot if -conf is given, otherwise -noboot.'
+  echo '  -conf             do configure before build.'
+  echo '                    Default is -noconf.'
+  echo '  -confopt string   configure options.'
+  echo '  -k                continue after an error?'
+  echo '                    Default is -nok.'
+  echo '  -j<option>        Option for a parallel make. Default is -noj.'
   echo '  -clean            indicates that all build/<variant> directories'
   echo '                    will be cleaned in order to start a clean build.'
   echo '                    Default is -noclean.'
@@ -482,6 +513,16 @@ if [ "$pkg" != "" ]; then
   PKGS="$PKGS $pkg#-v"
 fi
 
+# Check if variant part is given.
+for variant in $variants
+do
+  p1=`echo $variant | awk -F: '{print $1}'`
+  if [ "$p1" = "" ]; then
+    echo "Error: no variant part given in -build $variant"
+    exit 1
+  fi
+done
+
 # Check if in correct directory.
 curwd=`pwd`
 curwdl=`basename $curwd`
@@ -539,18 +580,20 @@ do
 done
 \rm -f allpkg.tmp
 
-# Now check out/update the full package.
-if [ $update != 0 ]; then
-  for PKG in $PKGS
-  do
-    pkg=`echo $PKG | sed -e 's%#-v.*%%'`
-    vers=`echo $PKG | sed -e 's%.*#-v%%'`
-    rtag=
-    tagstr=
-    if [ "$vers" != "" ]; then
-      rtag=-r$vers
-      tagstr=", cvstag $vers"
-    fi
+# Now check out/update the full package and show its name.
+for PKG in $PKGS
+do
+  pkg=`echo $PKG | sed -e 's%#-v.*%%'`
+  vers=`echo $PKG | sed -e 's%.*#-v%%'`
+  rtag=
+  tagstr=
+  if [ "$vers" != "" ]; then
+    rtag=-r$vers
+    tagstr=", cvstag $vers"
+  fi
+  if [ $update = 0 ]; then
+    echo "Needs package $pkg$tagstr"
+  else
     echo "Full update of package $pkg$tagstr"
     echo "$cvscomm update -dAP $rtag $updq $pkg" >> rub.log 2>&1
     $cvscomm update -dAP $rtag $updq $pkg >> rub.log 2>&1
@@ -558,7 +601,9 @@ if [ $update != 0 ]; then
     if [ $status != 0 ]; then
       echo "Exiting; update/checkout returned with an error status ..."
     fi
-  done
+  fi
+done
+if [ $update != 0 ]; then
   echo "See rub.log for the cvs update/checkout details"
   egrep "^C " rub.log > greplog.tmp 2>&1
   if [ $? = 0 ]; then
@@ -575,100 +620,105 @@ fi
 echo "Created lofarconf.in.private containing all these packages"
 pkgs=`sed -e s/#.*$//g lofarconf.in.private`
 
-if [ "$variants" = "" ]; then
-  echo "No build to be done"
-  exit 0
-fi
-
 # System build is a bit different.
 if [ "$system" != 0 ]; then
+  if [ "$variants" = "" ]; then
+    echo "No build to be done"
+    exit 0
+  fi
+  # Check if only 'normal' variants (no colons) are given.
+  for variant in $variants
+  do
+    atemp=`echo $variant | sed -e 's/://'`
+    if [ "$atemp" != "$variant" ]; then
+      echo "-system can only be given with variants containing no : specification"
+      exit 1
+    fi
+  done
   $pgmpath/buildsys -confopt "$confopt" -checktool "$checktool" "$variants" "$pkgs"
   exit 0
 fi
 
 # Determine the build commands.
-echo "Variants to be built: $variants"
 echo "See build.log for build details"
-bootcmd=
-confcmd=
-premake=
-mainmake=date
-postmake=
+\rm build.log
+touch build.log
+
+# Do bootstrap if needed.
 # Make sure bootstrap is executable; Eclipse does not set x bit.
 # Remove the cache, because sometimes it keeps old data.
+if [ $boot = 1 ]; then
+  for pkg in $pkgs
+  do
+    echo "" >> build.log
+    echo "  bootstrapping package $pkg ..."
+    (cd $pkg && rm -rf autom4te.cache && chmod +x bootstrap && ./bootstrap;) >> build.log 2>&1
+  done
+  echo "" >> build.log
+fi
+
+# See if anything has to be built.
+if [ "$variants" = "" ]; then
+  echo "No build to be done"
+  exit 0
+fi
+echo "Variants to be built: $variants"
+
+# Assemble the build options.    
+bopt="$kopt"
 if [ $conf = 1 ]; then
-  bootcmd="\\rm -rf autom4te.cache; chmod +x bootstrap && ./bootstrap && "
-  confcmd="../../lofarconf $confopt && "
-  echo "Packages will be bootstrapped and configured"
+  bopt="$bopt -conf"
+  if [ "$confopt" != "" ]; then
+    bopt="$bopt -confopt $confopt"
+  fi
+  echo "  Packages will be configured"
 fi
 if [ $clean = 1 ]; then
-  premake="make clean && "
-  echo "Packages will be cleaned"
+  bopt="$bopt -clean"
+  echo "  Packages will be cleaned"
 elif [ $clean = 2 ]; then
-  premake="make distclean && ../../lofarconf $confopt && "
-  echo "Packages will be distcleaned"
+  bopt="$bopt -distclean"
+  echo "  Packages will be distcleaned"
 fi
-if [ $buildmake = 1 ]; then
-  mainmake="date && make $jobsopt "
-  echo "Packages will be built"
+if [ $buildmake = 0 ]; then
+  bopt="$bopt -nomake"
+else
+  echo "  Packages will be built"
   if [ $check = 1 ]; then
     if [ "$checktool" = "" ]; then
-      postmake="&& make check "
-      echo "Packages will be checked"
+      bopt="$bopt -check"
+      echo "  Packages will be checked"
     else
-      postmake="&& make CHECKTOOL='$checktool' check "
-      echo "Packages will be checked with '$checktool'"
+      bopt="$bopt -checktool $checktool"
+      echo "  Packages will be checked with '$checktool'"
     fi
   fi
   if [ $install = 1 ]; then
-    postmake="$postmake && make install "
-    echo "Packages will be installed"
+    bopt="$bopt -install"
+    echo "  Packages will be installed"
   fi
   if [ $distcheck = 1 ]; then
-    postmake="$postmake && make distcheck "
-    echo "Packages will be distcheck-ed"
+    bopt="$bopt -distcheck"
+    echo "  Packages will be distcheck-ed"
   fi
   if [ $rpm = 1 ]; then
-    postmake="$postmake && make rpm "
-    echo "Packages will be rpm-ed"
+    bopt="$bopt -rpm"
+    echo "  Packages will be rpm-ed"
   fi
 fi
 
 # Build all variants.
-if [ $skipbuilt = 0 ]; then
-  # Start fresh, so delete results from previous builds.
-  \rm -f build.log build.result.*
-  touch build.log
-fi
 for variant in $variants
 do
-  echo "Building packages in build/$variant ..."
-  echo "" >> build.log
-  echo "***** Building packages in build/$variant ..." >> build.log
-  touch build.result.$variant
-  for pkg in $pkgs
-  do
-    if [ $skipbuilt = 1 ]; then
-      fgrep "$pkg " build.result.$variant >& /dev/null
-      if [ $? = 0 ]; then
-        echo "  skipping package $pkg; already built in a previous run"
-        continue
-      fi
-    fi
-    echo "  building package $pkg ..."
-    echo "" >> build.log
-    echo " *** Building package $pkg ***" >> build.log
-    echo "(cd $pkg && mkdir -p build/$variant && $bootcmd cd build/$variant && $confcmd $premake $mainmake $postmake;)" >> build.log
-    if [ $buildmake = 1 ]; then
-      eval "(cd $pkg && mkdir -p build/$variant && $bootcmd cd build/$variant && $confcmd $premake $mainmake $postmake && echo $pkg '# built at' `date` >> $curwd/build.result.$variant;)" >> build.log 2>&1
-      status=$?
-    else
-      eval "(cd $pkg && mkdir -p build/$variant && $bootcmd cd build/$variant && $confcmd $premake $mainmake $postmake;)" >> build.log 2>&1
-      status=$?
-    fi
-    if [ "$status" != 0 ]; then
-      echo " Error during build (see build.log for details)"
-      exit $status
-    fi
-  done
+  # See if a remote build has to be done.
+  p1=`echo $variant | awk -F: '{print $1}'`
+  p2=`echo $variant | awk -F: '{print $2}'`
+  p3=`echo $variant | awk -F: '{print $3}'`
+  if [ "$p2" = "" ]; then
+    # No user@machine given, so do the build locally.
+    $pgmpath/rubbuild $bopt -build "$p1:$p3" $pkgs
+  else
+    echo "Invoking build on $p2 ..."
+    ssh -x $p2 $pgmpath/rubbuild -bg -srcdir `pwd` $bopt -build "$p1:$p3" $pkgs
+  fi
 done
