bug 1326: Made it possible to supply a list of target directories (using -dirs)

diff --git a/trunk/CEP/Imager/MWCommon/src/startdistproc b/trunk/CEP/Imager/MWCommon/src/startdistproc
--- a/trunk/CEP/Imager/MWCommon/src/startdistproc
+++ b/trunk/CEP/Imager/MWCommon/src/startdistproc
@@ -12,7 +12,7 @@
 # It can use sockets or MPI.
 # The VdsDesc and ClusterDesc files are used to determine on which nodes
 # the various processes need to be started.
-# Possible arguments can be given after the program namw. They are given as
+# Possible arguments can be given after the program name. They are given as
 # arguments to the distributed programs.
 
 
@@ -26,6 +26,7 @@ wait=1
 dsn=
 cdn=
 hfn=
+dirs=
 fdp=
 master=localhost
 startmaster=1
@@ -59,6 +60,13 @@ do
   elif [ "$1" = "-nohfn" ]; then
     shift
     hfn=
+  elif [ "$1" = "-dirs" ]; then
+    shift
+    dirs="$1"
+    shift
+  elif [ "$1" = "-nodirs" ]; then
+    shift
+    dirs=
   elif [ "$1" = "-fdp" ]; then
     shift
     fdp="$1"
@@ -124,18 +132,24 @@ done
 
 if [ $help = 1 ]; then
   echo ''
-  echo 'startdistproc starts a distributed process to process the given dataset.'
+  echo 'startdistproc starts distributed processes to process a given dataset.'
   echo 'The mode tells if it is started through MPI, sockets, or as a single process.'
   echo ''
   echo 'Run as:'
-  echo ' startdistproc -dsn datasetname -cdn clusterdescname [-mode mode]'
+  echo ' startdistproc -cdn clusterdescname [-dsn datasetname]"
+  echo "              [-dirs directories] [-mode mode]'
   echo '              [-hfn hostfilename] [-fdp finddproc-path]'
   echo '              [-logfile logfilename] [-[no]dry]'
   echo '              [-extrahosts "host1 host2 ..."] [-noextrahosts]'
   echo '              [-masterhost host] [-startmaster] program [arg1 arg2 ...]'
   echo ''
-  echo '  -dsn datasetname      The name of the file describing the distributed dataset.'
   echo '  -cdn clusterdescname  The name of the file describing the cluster.'
+  echo '  -dsn datasetname      The name of the file describing the distributed dataset.'
+  echo '  -dirs directories     Directories to use if -dsn is not given.'
+  echo '                        Each directory can be preceeded by host: (a la scp).'
+  echo '                        This is useful if a distributed dataset has'
+  echo '                        to be created for which no VDS file exists yet.'
+  echo '                        -dsn and dirs cannot be given both.'
   echo '  -hfn hostfilename     The name of the generated hostfile.'
   echo '                        It defaults to /tmp/machinefile_$$'
   echo '  -fdp finddproc-path   Path where to find finddistproc.'
@@ -169,8 +183,12 @@ if [ "$program" = "" ]; then
   echo "Error: no program name given  ('startdistproc -h' gives help)"
   exit 1
 fi
-if test "$dsn" = ""; then
-  echo "Error: no dataset name given (use -dsn)"
+if test "$dsn" = ""  -a  "$dirs" = ""; then
+  echo "Error: dataset name nor directories given (use -dsn or -dirs)"
+  exit 1
+fi
+if test "$dsn" != ""  -a  "$dirs" != ""; then
+  echo "Error: dataset name and directories given both (use -dsn or -dirs)"
   exit 1
 fi
 if test "$cdn" = ""; then
@@ -182,10 +200,6 @@ if test $startmaster = 0; then
     echo "Error: -nostartmaster cannot be used with mode=mpi or single"
     exit 1
   fi
-fi
-if test ! -f "$dsn"; then
-  echo "Error: dataset $dsn not found"
-  exit 1
 fi
 if test ! -f "$cdn"; then
   echo "Error: clusterdesc $cdn not found"
@@ -204,7 +218,16 @@ masterh=$master
 if test $startmaster = 0; then
   masterh=
 fi
-${fdp}finddproc $dsn $cdn $masterh $extra > $hfn || exit 1
+# If a dataset name is given, find out where to process it.
+if test "$dsn" != ""; then
+  if test ! -f "$dsn"; then
+    echo "Error: dataset $dsn not found"
+    exit 1
+  fi
+  ${fdp}finddproc $dsn $cdn $masterh $extra > $hfn || exit 1
+else
+  ${fdp}finddproc -dirs "$dirs" $cdn $masterh $extra > $hfn || exit 1
+fi  
 np=`wc -l $hfn | awk '{print $1}'`
 
 # Run the program as needed.
@@ -224,3 +247,4 @@ else
   echo "socketrun $dry $hfn '$master' $modxx $wait $logfile $program" "$@"
   $pgmpath/socketrun $dry $hfn "$master" $modxx $wait "$logfile" $program "$@" || exit 1
 fi
+#rm -f $hfn
