%[ER:27]% Better handling of filenames, and support of interrupts

diff --git a/trunk/LCS/databases/AOD/src/genLCSbase b/trunk/LCS/databases/AOD/src/genLCSbase
--- a/trunk/LCS/databases/AOD/src/genLCSbase
+++ b/trunk/LCS/databases/AOD/src/genLCSbase
@@ -32,11 +32,11 @@ VERSION="v1.1"
 
 #---------------------------- Global routines ---------------------------------
 #
-# InitResultFile
+# initResultFile
 #
 # Adds an informational header to the result files
 #
-InitResultFile()
+initResultFile()
 {
 	echo -n "# This file was generated by genLCSbase ${VERSION} on " ; date
 	echo "# with the command: genLCSbase ${MODULE} <headerfiles>"
@@ -45,6 +45,18 @@ InitResultFile()
 	echo "# PLEASE COMPLETE THIS FILE AND REMOVE THE .proto EXTENSION"
 	echo "# IT MIGHT BE OVERWRITTEN THE NEXT TIME YOU RUN genLCSbase"
 	echo "#"
+}
+
+#
+# cleanupWorkFiles
+#
+# Removes all temporary workfiles
+#
+cleanupWorkFiles()
+{
+	rm -f ${ADDINGWORKFILE} ${FUNCTIONWORKFILE} ${GREPWORKFILE}	\
+		  ${MAPPEDWORKFILE} ${MEMBERWORKFILE}   ${MISSINGWORKFILE}	\
+		  ${NEEDEDWORKFILE} ${TYPEDEFWORKFILE}
 }
 
 #
@@ -75,7 +87,9 @@ analyseInfoFile()
 	# a pattern the corresponding code is executed. In this way awk is
 	# used as a kind of lex and yacc.
 
-	awk '
+	awk -v TYPEDEFFILE=${TYPEDEFWORKFILE} 		\
+		-v FUNCTIONFILE=${FUNCTIONWORKFILE}		\
+		-v MEMBERFILE=${MEMBERWORKFILE}		'
 	# First define some functions for handling difficult actions
 
 	#
@@ -128,7 +142,7 @@ analyseInfoFile()
 			}
 		}
 		gsub ("[ \t]+", " ", theTD)				# remove double spaces
-		print theTD >> "typedefs.LCS"
+		print theTD >> TYPEDEFFILE
 	}
 
 	#
@@ -146,7 +160,7 @@ analyseInfoFile()
 				theFunct=theFunct getTillNext("}");
 			}
 		}
-		print theFunct >> "functions.LCS"
+		print theFunct >> FUNCTIONFILE
 	}
 
 	#
@@ -237,7 +251,7 @@ analyseInfoFile()
 							  # end the class definition with a marker
 							  # the contains the filename and the classname
 							  # note: the class MUST be on a non-existing place
-							  printf "%s@@@@@%s@\n", File , Class >"members.LCS"
+							  printf "%s@@@@@%s@\n", File , Class >MEMBERFILE
 							}
 							Class=substr(prevName,2)
 						  }
@@ -254,7 +268,7 @@ analyseInfoFile()
 	  }
 
 	  # This must be a variable declaration
-	  printf "%s@%s@%s@%s@%s\n", File, NameSpace, Class, Mode, $0 >"members.LCS"
+	  printf "%s@%s@%s@%s@%s\n", File, NameSpace, Class, Mode, $0 >MEMBERFILE
 	  nrMembers++
 	}
 	'
@@ -279,7 +293,12 @@ addToMapFile()
 		# grep @class@ or @class : public xxx@
 		grepmask="@$2[ \t:publiclastru]*[a-zA-Z0-9_]*@"
 	fi
-	eval "grep '$grepmask' $1" | awk '
+	eval "grep '$grepmask' $1" | \
+
+	awk -v TYPEDEFFILE=${TYPEDEFWORKFILE}	\
+		-v GREPFILE=${GREPWORKFILE}			\
+		-v MAPPEDFILE=${MAPPEDWORKFILE}		\
+		-v NEEDEDFILE=${NEEDEDWORKFILE}	'
 
 	BEGIN {
 		prevClass="NoSuchClass"
@@ -334,12 +353,12 @@ addToMapFile()
 	function resolveTypedef(varType,   theTypedef) {
 		# note: the get a result from a system command into awk we must
 		# pass it to a file and then read the file again.
-		Command=sprintf("grep %c %s;%c typedefs.LCS >tmp.LCS 2>/dev/null", 39, varType, 39);
+		Command=sprintf("grep %c %s;%c %s >%s 2>/dev/null", 39, varType, 39, TYPEDEFFILE, GREPFILE);
 		system(Command)							# execute grep
 
 		theTypedef=""							# reset result
-		getline theTypedef <"tmp.LCS"			# get grep result
-		close("tmp.LCS")						# not needed anymore
+		getline theTypedef < GREPFILE			# get grep result
+		close(GREPFILE)						# not needed anymore
 		if (length(theTypedef) <= 0) {			# not found?
 			return "@@@"						# return failure
 		}
@@ -483,10 +502,10 @@ addToMapFile()
 			prevBaseClass=BaseClass
 
 			# remember this class is in the map file
-			print Class >>"mapped.LCS"
+			print Class >>MAPPEDFILE
 
 			if (BaseClass != "") {
-				print BaseClass >>"needed.LCS"		# add this class later
+				print BaseClass >>NEEDEDFILE		# add this class later
 			}
 		}
 
@@ -497,15 +516,15 @@ addToMapFile()
 
 		printf "%-18s %-18s %-18s %s\n", MemberType, MemberName, ColumnName, ColumnType
 		if (ColumnName == "Class" || ColumnName == "BaseClass") {
-			print substr(ColumnType,4) >>"needed.LCS"
+			print substr(ColumnType,4) >>NEEDEDFILE
 		}
 	} '
 }
 
 #
-# ConstructFunfile usedClassesFile
+# constructFunfile usedClassesFile
 #
-ConstructFunfile()
+constructFunfile()
 {
 	grep -v "#" $1 | sort | uniq | awk '{
 		printf "%-15s		I\n", $1
@@ -517,10 +536,28 @@ ConstructFunfile()
 
 #------------------------------- MAIN ----------------------------------------
 #
-# Check invocation syntax: genLCSbase module headerfiles
+# Syntax: genLCSbase [-d destdir] module headerfiles
 #
+
+DESTDIR="./"
+
+# Check invocation syntax
+#
+eval set argv=`getopt "d:" $*`			# reformat arguments
+shift
+case "$1" in
+	-d) DESTDIR=$2
+		if [ ! -d ${DESTDIR} ]; then
+			echo "Destination directory >${DESTDIR}< does not exist"
+			exit 1
+		fi
+		shift 2
+		;;
+esac
+shift									# remove --
+
 case $# in
-	0|1)	echo "Syntax: $0 module headerfiles"
+	0|1)	echo "Syntax: $0 [-d destdir] module headerfiles"
 		exit 0
 		;;
 	*)	MODULE=$1
@@ -531,81 +568,95 @@ esac
 
 # Initialize some variables
 #
-MAPFILE=${MODULE}.map.proto
-FUNFILE=${MODULE}.fun.proto
+MAPFILE=${DESTDIR}/${MODULE}.map.proto		# resultfile
+FUNFILE=${DESTDIR}/${MODULE}.fun.proto		# resultfile
+
+# A lot of temp files but this makes life much easier
+ADDINGWORKFILE=/tmp/adding.LCS.$$			# subclasses curr. adding
+FUNCTIONWORKFILE=/tmp/functions.LCS.$$		# functions in the inputfile
+GREPWORKFILE=/tmp/grep.LCS.$$				# tmp grep result
+MAPPEDWORKFILE=/tmp/mapped.LCS.$$			# classes already mapped
+MEMBERWORKFILE=/tmp/members.LCS.$$			# datamembers in the inputfile
+MISSINGWORKFILE=/tmp/missing.LCS.$$			# classes not in the inputfile
+NEEDEDWORKFILE=/tmp/needed.LCS.$$			# subclasses to add later
+TYPEDEFWORKFILE=/tmp/typedefs.LCS.$$		# typedefs in the inputfile
+
+# make sure there are no old workfiles left
+cleanupWorkFiles
+
+# Set trap handler before we create anything
+trap "cleanupWorkFiles ; exit" 1 2 3 13 15
 
 # Write headers to the result files.
-InitResultFile  	> ${MAPFILE}
-InitResultFile  	> ${FUNFILE}
-
-# make sure there are no old overall results left
-rm -f mapped.LCS missing.LCS
+initResultFile  	> ${MAPFILE}
+initResultFile  	> ${FUNFILE}
 
 # Scan the headerfiles and substract the class hierarchy
 for file in ${HEADERFILES}
 do
 	# cleanup intermediate results
-	rm -f typedefs.LCS functions.LCS members.LCS needed.LCS
+	rm -f ${TYPEDEFWORKFILE} ${FUNCTIONWORKFILE} ${MEMBERWORKFILE} \
+		  ${NEEDEDWORKFILE}
 
 	# First stage: break down precompiled headerfile into:
-	#		typedefs.LCS
-	#		functions.LCS
-	#		members.LCS
+	#		typedefs.LCS.$$
+	#		functions.LCS.$$
+	#		members.LCS.$$
 	echo -n "${file}: analysing"
 	cleanlist $file | analyseInfoFile
 
 	# Second stage: Construct mapfile from all classes in main headerfile
-	#	This stage might produce a needed.LCS file.
+	#	This stage might produce a needed.LCS.$$ file.
 	echo -n ", adding main classes"
-	addToMapFile members.LCS >>${MAPFILE}
+	addToMapFile ${MEMBERWORKFILE} >>${MAPFILE}
 
 	# Third stage (repeating): Add the base- and embedded- classes
 	echo -n ", adding base classes"
 	complete=false
 	while (! $complete)
 	do
-		if [ ! -f "needed.LCS" ]; then		# nothing needed anymore?
-			complete=true					# then we are done
+		if [ ! -f "${NEEDEDWORKFILE}" ]; then	# nothing needed anymore?
+			complete=true						# then we are done
 			break
 		fi
 
-		sort needed.LCS | uniq >adding.LCS	# skip doubles
-		rm -f needed.LCS					# will be recreated in next loop
-		cat adding.LCS | while read classname
+		sort ${NEEDEDWORKFILE} | uniq >${ADDINGWORKFILE} 	# skip doubles
+		rm -f ${NEEDEDWORKFILE}				# will be recreated in next loop
+		cat ${ADDINGWORKFILE} | while read classname
 		do
 			# make sure this class is not already in the map file
-			grep $classname mapped.LCS >/dev/null 2>&1
+			grep $classname ${MAPPEDWORKFILE} >/dev/null 2>&1
 			if [ $? -ne 0 ]; then			# not found?
-				addToMapFile members.LCS $classname >>${MAPFILE}
+				addToMapFile ${MEMBERWORKFILE} $classname >>${MAPFILE}
 				# class succesfully added?
-				grep $classname mapped.LCS >/dev/null 2>&1
+				grep $classname ${MAPPEDWORKFILE} >/dev/null 2>&1
 				if [ $? -ne 0 ]; then		# still not found?
-					echo $classname >>missing.LCS
+					echo $classname >>${MISSINGWORKFILE}
 				fi
 			fi
 		done
-		rm adding.LCS
+		rm ${ADDINGWORKFILE}
 	done
 	echo ", ready"
 done
 
-# The embedded and base classes are still in the map file like @@@xxx
+# The embedded and base classes are still in the map file as @@@xxx
 # Remove the @@@ from the classes that were resolved.
-cat mapped.LCS | while read class
+cat ${MAPPEDWORKFILE} | while read class
 do
 	cat ${MAPFILE} | sed "s/@@@${class}$/${class}/" >> ${MAPFILE}tmp
 	mv ${MAPFILE}tmp ${MAPFILE}
 done
 
 # Almost done, construct the fun file for the implemented classes
-ConstructFunfile mapped.LCS >>${FUNFILE}
+constructFunfile ${MAPPEDWORKFILE} >>${FUNFILE}
 
-if [ -f missing.LCS ]; then
+# Notify user for missing sub classes
+if [ -f ${MISSINGWORKFILE} ]; then
 	echo "WARNING: The following types or classes could not be resolved:"
-	cat missing.LCS
+	cat ${MISSINGWORKFILE}
 fi
 
 # Finally cleanup our mess.
-#rm -f typedefs.LCS functions.LCS members.LCS needed.LCS mapped.LCS missing.LCS
-
+cleanupWorkFiles
 
