Bug 1642: Adapted scripts

diff --git a/trunk/MAC/Deployment/data/OTDB/loadPICtree b/trunk/MAC/Deployment/data/OTDB/loadPICtree
--- a/trunk/MAC/Deployment/data/OTDB/loadPICtree
+++ b/trunk/MAC/Deployment/data/OTDB/loadPICtree
@@ -1,4 +1,4 @@
-#!/usr/bin/ksh
+#!/bin/bash
 #
 # loadPICtree : loads all components in an OTDB database
 #
@@ -34,23 +34,61 @@ SyntaxError()
 
 	[ -z "${Msg}" ] || echo "ERROR: ${Msg}"
 	echo ""
-	echo "Syntax: $(basename $0) databasename"
-	echo ""
-	exit 1
+	echo "Syntax: $(basename $0) -D databasename [-H databaseserver] [-D directory]"
+	echo "        - databasename is always needed"
+        echo "        - directory is path to executables PVSS2SAS and load_PICtree"
+	echo
 }
+
+DATABASE=
+HOST=`hostname -s`
+DIR="/opt/lofar/bin"
+
+while getopts "hD:v:q:H:d:" OPTION
+do
+     case $OPTION in
+
+         h)
+             SyntaxError
+             exit 1
+             ;;
+	 D)
+	     DATABASE=$OPTARG
+	     ;;
+	 H)
+	     HOST=$OPTARG
+	     ;;
+	 d)
+	     DIR=$OPTARG
+	     ;;
+	 ?)
+             SyntaxError
+             exit 1
+             ;;
+       esac
+done
+
+if [[ -z $DATABASE ]]; then 
+  echo "Please provide a database name!"
+  SyntaxError
+  exit
+fi
 
 #
 # MAIN
 #
 
-# check invocation syntax
-if [ $# -ne 1 ]; then
-	SyntaxError
+if [[ -e $DIR/PVSS2SAS ]] && [[ -e $DIR/load_PICtree ]]; then 
+  RESULTFILE=OTDBDatapoints.out
+  rm -f ${RESULTFILE}
+  echo "Creating PIC file..."
+  ./createPICfile | $DIR/PVSS2SAS >${RESULTFILE}
+  # create commandline for load_PICtree
+  arguments=$DATABASE
+  arguments=$arguments" "$HOST
+  echo "Executing: $DIR/load_PICtree $arguments ${RESULTFILE} 2>&1 | tee loadPICtree.log"
+  $DIR/load_PICtree $arguments ${RESULTFILE} 2>&1 | tee loadPICtree.log
+  echo "Done"
+else
+  echo "Cannot find or execute $DIR/PVSS2SAS or $DIR/load_PICtree"
 fi
-
-RESULTFILE=OTDBDatapoints.out
-
-rm -f ${RESULTFILE}
-echo "Creating PIC file..."
-./createPICfile | /home/coolen/data/LOFAR/installed/gnu_debug/bin/PVSS2SAS >${RESULTFILE}
-/home/coolen/data/LOFAR/installed/gnu_debug/bin/load_PICtree $1 ${RESULTFILE}
