Task #5624: Adapted swlevel to not start RSP/TBB when problem loading images. Swlevel uses the new RSPDriver.XST_FIRST_RSP_BOARD flag to determine first board to start loading images

diff --git a/branches/MAC-Swlevel-Task5624/MAC/APL/APLCommon/src/swlevel b/branches/MAC-Swlevel-Task5624/MAC/APL/APLCommon/src/swlevel
--- a/branches/MAC-Swlevel-Task5624/MAC/APL/APLCommon/src/swlevel
+++ b/branches/MAC-Swlevel-Task5624/MAC/APL/APLCommon/src/swlevel
@@ -74,29 +74,6 @@ SyntaxError()
 # Method to run a command with a specified timeout in seconds
 # First argument is timeout, next arguments are the command and its parameters
 
-run_timeout()
-{
-    timeout=$1 # in seconds
-    interval=1
-    delay=1
-    shift ${argv}
-    (
-        ((t = timeout))
-
-        while ((t > 0)); do
-            sleep $interval
-            kill -0 $$ || exit 0
-            ((t -= interval))
-        done
-
-        # Be nice, post SIGTERM first.
-        # The 'exit 0' below will be executed if any preceeding command fails.
-        kill -s SIGTERM $$ && kill -0 $$ || exit 0
-        sleep $delay
-        kill -s SIGKILL $$
-    ) 2> /dev/null &
-    exec "$@"
-}
 
 # Find which image to load on a given station; uses file 
 # ${ETCDIR}/RSPImage.conf
@@ -133,6 +110,7 @@ findImage()
 selectImage()
 {
 	let nrRSPs=`grep RSPBOARDS ${ETCDIR}/RemoteStation.conf | cut -d'=' -f2 | sed 's/ //g'`
+        let offset=0x`grep RSPDriver.MAC_ADDR_0 ${ETCDIR}/RSPDriver.conf | cut -d'=' -f2 | cut -d':' -f5`
 	let board=0
         # Assume no errors with board communication
 	boardError=0
@@ -145,19 +123,21 @@ selectImage()
 	while [ $board -lt $nrRSPs ]
 	do
 		# get major version of active firmware on RSPboard $board
-		boardHex=`echo $board | awk '{ printf "%02x", $1 }'`
+                #boardHex=`echo $board | awk '{ printf "%02x", $1 }'` 
+		boardHex=`echo $board | awk -v firstBoard=$offset '{ printf "%02x", firstBoard+$1 }'`
 		rsu=`run_timeout.sh 5 sudo ${BINDIR}/../sbin/rsuctl3 -m 10:fa:00:00:$boardHex:00 -qV 2>&1 | grep BP | cut -d':' -f2 | sed 's/ //g' | cut -d'.' -f1`
 
 		# If not a single number, something weird  must have happened
 		if [ ${#rsu} -ne 1 ]; then 
-                  echo "RSPboard $board: Error requesting active firmware version (communication error)"
+                  echo "RSPboard $boardHex: Error requesting active firmware version (communication error)"
 		  boardError=1
+		  errorBoards=${errorBoards}${boardHex}","
                 else
-  		  echo "Loading image $image on RSPboard $board ..."
+  		  echo "Loading image $image on RSPboard $boardHex ..."
 		  run_timeout.sh 5 sudo ${BINDIR}/../sbin/rsuctl3_reset -m 10:fa:00:00:$boardHex:00 -q -x -p $image 1>/dev/null 2>&1
                   if [ $? -ne 0 ]; then 
 		      boardError=1
-                      errorBoards=${errorBoards}${board}","
+                      errorBoards=${errorBoards}${boardHex}","
                   fi
 		fi
 		# Next board
@@ -165,6 +145,7 @@ selectImage()
 	done
 	if [ $boardError -eq 1 ]; then
 	    echo "Board(s) $errorBoards have a communication problem; try reset the 48V"
+	    exit 1 # This is needed to prevent RSP/TBB drivers from starting up in case of error!
 	fi
 }
 
@@ -216,7 +197,7 @@ start_prog()
 		       sudo rm -f $LOGDIR/$prog.log.? 1>/dev/null 2>&1
 		       if [ "$prog" = "RSPDriver" ]; then
 			   selectImage
-                       fi
+		       fi
 		       sudo -b $BINDIR/$prog 1>>$LOGDIR/$prog.stdout.${curdate} 2>&1
 		    else
 			echo Starting $prog
@@ -526,6 +507,9 @@ goto_level()
 			start_prog $program x$asroot x$withmpi
                         ) <&- # cant have programs reading from stdin
                               # as that would mess up 'while read line'
+			if [ $? -eq 1 ]; then
+			    break
+			fi
 	       done
 	done
 }
