TAsk #3772: Merged trunk into task branch prior to reintegrate

diff --git a/branches/LOFAR-Pulp-Integration-Task3772/MAC/Deployment/data/OTDB/loadComponents b/branches/LOFAR-Pulp-Integration-Task3772/MAC/Deployment/data/OTDB/loadComponents
--- a/branches/LOFAR-Pulp-Integration-Task3772/MAC/Deployment/data/OTDB/loadComponents
+++ b/branches/LOFAR-Pulp-Integration-Task3772/MAC/Deployment/data/OTDB/loadComponents
@@ -35,13 +35,16 @@ SyntaxError()
 	[ -z "${Msg}" ] || echo "ERROR: ${Msg}"
 	echo ""
 	echo "Syntax: $(basename $0) -D databasename [-v versionnr] [-q qualifier]" 
-	echo "                       [-H hostname] [-d directory] [-l]"
-	echo "        - if database name is empty, only tmp files are created (for comparison)"
-	echo "        - versionnumber is svn revision number (max 6 digits) [Current]"
-	echo "        - qualifier can be development|test|operational|example []"
-	echo "        - hostname is the hostname of the database server [sasdb]" 
-	echo "        - directory is the path to the executable load_OTDB_comps [/opt/lofar/bin]"
-        echo "        - Option -l says this is run locally in a checked out SVN tree"
+	echo "                       [-H hostname] [-d execdir] [-c compdir] "
+	echo "                       [-o logfile ] [-l]"
+	echo "  - if database name is empty, only tmp files are created (for comparison)"
+	echo "  - versionnumber is svn revision number (max 6 digits) [Current]"
+	echo "  - qualifier can be development|test|operational|example []"
+	echo "  - hostname is the hostname of the database server [localhost]" 
+	echo "  - execdir is the path to the executable load_OTDB_comps  (searches in PATH)"
+	echo "  - compdir is the directory of the component files [./]"
+	echo "  - logfile is logfile name with path [/opt/lofar/var/log/loadComponents.log]" 
+        echo "  - Option -l says this is run locally in your workspace (checked out SVN tree)"
 	echo ""
 }
 # Replace the placeholder @VERSION@ in file Version.comp.tmpl by the version
@@ -146,12 +149,13 @@ makeOrderFile()
 DATABASE=
 VERSION=
 QUAL=
-HOST='sasdb'
-DIR="/opt/lofar/bin"
+HOST="localhost"
+DIR=
 localUse=0
 DB_Update=1
-wdir="/opt/lofar/etc/otdb" # default location of comp, gcomp files 
-while getopts "hD:v:q:H:d:l" OPTION
+wdir="." # default location of comp, gcomp files
+logfile="/opt/lofar/var/log/loadComponents.log"
+while getopts "hD:v:q:H:d:c:o:l" OPTION
 do
      case $OPTION in
 
@@ -171,12 +175,18 @@ do
 	 H)
 	     HOST=$OPTARG
 	     ;;
-	 d)
-	     DIR=$OPTARG      
+	 d)  
+	     DIR=$OPTARG    
 	     ;;
-         l)  localUse=1
-             wdir="." 
+         c)
+	     wdir=$OPTARG
 	     ;;
+         l)  
+	     localUse=1
+	     ;;
+         o)
+             logfile=$OPTARG
+             ;;
 	 ?)
              SyntaxError
              exit 1
@@ -240,7 +250,20 @@ fi
   rm -f ${RELATIONSFILE} ${LEVELFILE}
 
 if [ $DB_Update -eq 1 ]; then
-  if [ -x $DIR/load_OTDB_comps ]; then 
+  if [ "$DIR" != "" ]; then
+    prog=$DIR/load_OTDB_comps
+    if [ ! -e $prog ]; then 
+      echo "Cannot find $prog"
+      exit
+    fi
+  else
+    prog=`which load_OTDB_comps 2>/dev/null`
+    if [ $? != 0 ]; then
+      echo "Cannot find load_OTDB_comps in PATH"
+      exit    
+    fi
+  fi
+  if [ -x $prog ]; then 
     # Construct commandline for load_OTDB_comps
     arguments=$DATABASE
     arguments=$arguments" "${ORDERFILE}
@@ -249,14 +272,9 @@ if [ $DB_Update -eq 1 ]; then
     if [ "$QUAL" != "" ]; then 
       arguments=$arguments" -q "$QUAL 
     fi
-    if [ $localUse = 0 ]; then
-      logfile="/opt/lofar/var/log/loadComponents.log"
-    else
-      logfile="./loadComponents.log"
-    fi
-  
-    echo "Executing: load_OTDB_comps $arguments 2>&1 1>$logfile"
-    load_OTDB_comps $arguments 2>&1 1>$logfile
+
+    echo "Executing: $prog $arguments 2>&1 1>$logfile"
+    $prog $arguments 2>&1 1>$logfile
     # when there are files we didn't use report that to the user
     if [ -s ${UNUSEDFILES} ]; then
 	echo
@@ -268,7 +286,7 @@ if [ $DB_Update -eq 1 ]; then
     # Cleanup
     rm -f ${UNUSEDFILES} ${ORDERFILE}
   else
-    echo "Cannot execute load_OTDB_comps (not there, or not executable)"
+    echo "Cannot execute $prog (not executable)"
   fi
 else
   echo "All component files created; no database upload requested. See ${ORDERFILE} for used and ${UNUSEDFILES} for unused component files"
