Task #4360: Merge from trunk

diff --git a/branches/Cobalt-integrate-Task4360/CMake/testscripts/assay b/branches/Cobalt-integrate-Task4360/CMake/testscripts/assay
--- a/branches/Cobalt-integrate-Task4360/CMake/testscripts/assay
+++ b/branches/Cobalt-integrate-Task4360/CMake/testscripts/assay
@@ -142,6 +142,9 @@
   NEEDOUTFIL=$1
   shift
 
+# Get absolute directory of this script.
+  lfr_script_dir=$(cd "$(dirname "$0")" && pwd)
+
 # Use LimitExec if possible and available.
   LOFAR_LIMITEXEC=
   if [ -x "$LOFARROOT/bin/LimitExec" ]
@@ -203,9 +206,14 @@
     export LOFAR_CHECKTOOL
   fi
 
-# Execute the command.
-  eval "$COMMAND" > ${PROG}_tmp.out
-  STATUS=$?
+# Execute the command, and duplicate stdout to file. The challenge here is to
+# fetch the exit status of $COMMAND, not that of tee. There is an arcane POSIX
+# way of doing this (ref: http://stackoverflow.com/questions/2413166/
+# bash-redirect-and-append-stdout-and-stderr-to-file-and-terminal).
+  exec 4>&1
+  STATUS=$({ { eval "$COMMAND"; echo $? >&3; } | \
+             { tee ${PROG}_tmp.out >&4; } } 3>&1)
+  exec 4>&-
 
   # Check the status.
   case $STATUS in 
@@ -230,11 +238,6 @@
     ;;
   *) 
     echo "FAIL (execution failure): $PROG"
-    # We may want to know what went wrong, so we'll secure the log file
-    if [ -f ${PROG}_tmp.log ]
-    then
-      mv ${PROG}_tmp.log ${PROG}.err
-    fi
     exit
      ;;
   esac
