Task #4803: fix tMSWriterCorrelated.run.in test: don't try to set the env in a sub-shell, as pointed out by Marcel. (Was already broken before I touched this file; additional fixup.)

diff --git a/RTCP/Cobalt/OutputProc/test/tMSWriterCorrelated.run.in b/RTCP/Cobalt/OutputProc/test/tMSWriterCorrelated.run.in
--- a/RTCP/Cobalt/OutputProc/test/tMSWriterCorrelated.run.in
+++ b/RTCP/Cobalt/OutputProc/test/tMSWriterCorrelated.run.in
@@ -7,10 +7,10 @@ if [ $status -ne 0 ]; then
   exit $status
 fi
 
-# add path to casacore for lhn001, but don't fail or print crap if this does not work
-(
- . /opt/cep/login/bashrc && use LofIm
-) > /dev/null 2>&1 || true
+# add path to casacore's taql for lhn001, but don't fail or print crap if this does not work
+{
+  . /opt/cep/login/bashrc && use LofIm ;
+} > /dev/null 2>&1 || true
 
 # if taql is unavailable, don't do subsequent tests
 taql --help >/dev/null 2>&1
@@ -24,7 +24,7 @@ fi
 # Otherwise, the tables are not created, an exception is caught and printed,
 # but tMSWriterCorrelated returns 0. This will then fail (if taql is found).
 
-# The taql needs the storage manager library to read our LOFAR correlator MS output.
+# The taql needs the LOFAR storage manager library to read our LOFAR correlator MS output.
 export LD_LIBRARY_PATH=@CMAKE_BINARY_DIR@/RTCP/LofarStMan/src:$LD_LIBRARY_PATH
 taql 'select ELEMENT_FLAG[,0] from tMSWriterCorrelated.in_1/SB000.MS::LOFAR_ANTENNA_FIELD'
 
