%[ER:27]% Full functional implementation of doRetrieve, also for base-classes

diff --git a/LCS/databases/AOD/src/genLCScode b/LCS/databases/AOD/src/genLCScode
--- a/LCS/databases/AOD/src/genLCScode
+++ b/LCS/databases/AOD/src/genLCScode
@@ -6,7 +6,7 @@
 # Uses a .map file to lookup the references and a .fun file
 # for looking up the routines that should be generated
 #
-# Syntax: genDTL mapfile functionfile R|P [class]
+# Syntax: genLCScode mapfile functionfile R|P [class]
 #
 # $Id$
 #
@@ -251,13 +251,30 @@ TPOaddClassRedefinition()
 	echo "{"
 	echo "public:"
 
-	echo "	TPersistentObject() : TPersistentObjectBase<${Class}>() {};"
+	echo "	TPersistentObject() : TPersistentObjectBase<${Class}>()"
+	grep ^$Class ${MAPWRKFILE} | grep -v "::" | while read line
+	do
+		MemberName=`echo $line | cut -d':' -f4`
+		ColumnName=`echo $line | cut -d':' -f5`
+		if [ "${ColumnName}" = "BaseClass" ] ; then
+			echo "	, its${MemberName}TPO(this->value())"
+		else
+			echo "	, its${MemberName}TPO(this->value().${MemberName})"
+		fi
+	done
+	echo "{};"
+
 	echo "	explicit TPersistentObject(${Class}&	t) : TPersistentObjectBase<${Class}>(t)"
 	# This is where it all about:
 	grep ^$Class ${MAPWRKFILE} | grep -v "::" | while read line
 	do
 		MemberName=`echo $line | cut -d':' -f4`
-		echo "	, its${MemberName}TPO(t.${MemberName})"
+		ColumnName=`echo $line | cut -d':' -f5`
+		if [ "${ColumnName}" = "BaseClass" ] ; then
+			echo "	, its${MemberName}TPO(t)"
+		else
+			echo "	, its${MemberName}TPO(t.${MemberName})"
+		fi
 	done
 	echo "{};"
 
@@ -516,6 +533,69 @@ TPOcodeHandleAllSubclasses()
 	echo "	// We didn't ran into the catch, so everything went well"
 }
 
+#
+# TPOcodeRetrieveSubclasses class
+#
+# Adds code for retrieving the data of the subclasses
+# When the object has no subclasses a comment line is generated.
+#
+TPOcodeRetrieveSubclasses()
+{
+	Class=$1
+	Table=`grep ^$Class ${MAPWRKFILE} | head -1 | cut -d":" -f2`
+
+	# Grep all subclasses of this class.
+	# Note: grep returns 0 if something found, 1 or -1 if not.
+	grep ^$Class ${MAPWRKFILE} | grep -v "::" >>/dev/null
+	GrepOk=`echo $?`
+	
+	if [ ${GrepOk} != "0" ]; then			# nothing found?
+		echo "	// No subclasses"
+		return
+	fi
+
+	# There are subclasses construct a try-catch area
+	echo "	// Retrieve all subclasses"
+	echo "	try {"
+
+	# Call all subclasses
+	grep ^$Class ${MAPWRKFILE} | grep -v "::" | while read line
+	do
+		MClass=`echo $line | cut -d':' -f3`
+		Member=`echo $line | cut -d':' -f4`
+		echo "		Collection<TPersistentObject<${MClass}> > 	${Member}Result;"
+		echo "		Collection<TPersistentObject<${MClass}> >::iterator 	${Member}Iter;"
+		echo "		string ${Member}SqlStr(\"WHERE owner IN (SELECT ObjId from ${Table} \");"
+		echo "		${Member}SqlStr = ${Member}SqlStr + query.getSql() + \")\";"
+		echo "		${Member}Result = TPO${Class}.its${Member}TPO.doRetrieve(Query(${Member}SqlStr), 1);"
+		echo "		${Member}Iter = ${Member}Result.begin();"
+		echo ""
+		echo "		if (${Member}Iter != ${Member}Result.end()) {"
+		echo "			// make deep copy op data and metadata"
+		echo "			TPO${Class}.its${Member}TPO.value()    = (*${Member}Iter).value();"
+		echo "			TPO${Class}.its${Member}TPO.metaData() = (*${Member}Iter).metaData();"
+		echo "		}"
+	done
+
+	# Close the try and build the catch
+	echo "	}"
+	echo "	catch (${ErrName}Error&	errObj) {"
+	if [ "${Action}" == "Erase" ]; then
+		echo "		DBConnection::GetDefaultConnection().RollbackAll();"
+	fi
+	grep ^$Class ${MAPWRKFILE} | grep -v "::" | while read line
+	do
+		Member=`echo $line | cut -d':' -f4`
+#		echo "		PO_${Member}.rollback(theState);"
+	done
+	echo "		Collection<TPersistentObject<${Class}> >   emptyResult;"
+	echo "		return (emptyResult);"
+	echo "	}"
+	echo ""
+	echo "	// We didn't ran into the catch: add the instance to the collection"
+
+}
+
 
 #
 # TPOcodeGetDBTimestamp 
@@ -746,6 +826,7 @@ TPOaddSearchRoutine()
 		echo "const long			theState,\n							"
 	fi
 	echo "const Query&	query, int maxObjects) {"
+echo "	cout << \"doRetrieve ${Class}\" << endl;"
 	echo "	DBView<${Class}_DBRep>	selView(\"${Table}\", ${Class}_DTL_BCA(),"
 	echo "													query.getSql());"
 	echo "	DBView<${Class}_DBRep>::select_iterator	selIter = selView;"
@@ -760,6 +841,9 @@ TPOaddSearchRoutine()
 	echo "	for (int nrRecs = 0; selIter != selView.end() && nrRecs < maxObjects; ++selIter, ++nrRecs) {"
 	echo "		TPersistentObject<${Class}>		TPO${Class};"
 	echo "		TPO${Class}.fromDatabaseRep(*selIter);"
+
+	TPOcodeRetrieveSubclasses	${Class}
+
 	echo "		selResult.add(TPO${Class});"
 	echo "	}"
 	echo "		// @@@ TO BE DEFINED @@@"
@@ -782,8 +866,8 @@ TPOaddSearchRoutine()
 #
 initTmpfile()
 {
-	echo "#This temporarely file was generated by genDTL"
-	echo "#It should have been cleaned up by genDTL, please remove it"
+	echo "#This temporarely file was generated by genLCScode"
+	echo "#It should have been cleaned up by genLCScode, please remove it"
 	echo "#ClassName:TableName:Ctype:MemberName:ColumnName:SubclassName:DBtype"
 }
 
@@ -797,8 +881,8 @@ initSrcfile()
 	FileType=$1
 	Class=$2
 
-	echo -n "//# This file was generated by genDTL ${VERSION} on " ; date
-	echo "//# with the command: genDTL ${MAPFILE} ${FUNFILE} ${LAYER} ${CLASS}"
+	echo -n "//# This file was generated by genLCScode ${VERSION} on " ; date
+	echo "//# with the command: genLCScode ${MAPFILE} ${FUNFILE} ${LAYER} ${CLASS}"
 	echo -n "//# from the directory: " ; pwd
 	echo "//#"
 	echo "//# EDITING THIS FILE MANUALLY IS AT YOUR OWN RISK"
@@ -831,6 +915,7 @@ initSrcfile()
 			echo "#include <dtl/DTL.h>"
 		else
 			echo "#include <PL/TPersistentObject.h>"
+			echo "#include <PL/Collection.h>"
 			echo "#include <PL/SQLTimeStamp.h>"
 			echo "#include \"${Class}.h\""
 		fi
@@ -952,7 +1037,7 @@ hasSubClasses()
 }
 #------------------------------- MAIN program ---------------------------------
 #
-# Check invocation syntax: [-d destdir] genDTL mapfile cmdfile layer [class]
+# Check invocation syntax: [-d destdir] genLCScode mapfile cmdfile layer [class]
 #
 
 # Check option argument
@@ -972,13 +1057,13 @@ shift								# remove --
 
 # Check other arguments
 case $# in
-	3)	MAPFILE=$1					# genDTL mapfile funfile layer
+	3)	MAPFILE=$1					# genLCScode mapfile funfile layer
 		FUNFILE=$2
 		typeset -u LAYER=$3
 		GREPMASK=""
 		CLASS=""
 		;;
-	4)	MAPFILE=$1					# genDTL mapfile funfile layer classname
+	4)	MAPFILE=$1					# genLCScode mapfile funfile layer classname
 		FUNFILE=$2
 		typeset -u LAYER=$3
 		GREPMASK=" | grep ^$4"
@@ -1069,6 +1154,7 @@ do
 			SOURCEFILE=${DESTDIR}/${FILEPREFIX}${class}.tcc
 			HEADERFILE=${DESTDIR}/${FILEPREFIX}${class}.h
 			echo ${class}	 							>>${ALLCLASSESWRKFILE}
+			echo "Creating code for class ${class}"
 			initSrcfile "cc"				${class} 	> ${SOURCEFILE}
 			TPOopenNamespace							>>${SOURCEFILE}
 			TPOaddBCA 						${class} 	>>${SOURCEFILE}
