%[ER:27]% Rewrote script to support inheritance of classes. The script now expects a preprocessed header file (gcc -E) in stead of the headerfile.

diff --git a/LCS/databases/AOD/src/genLCSbase b/LCS/databases/AOD/src/genLCSbase
--- a/LCS/databases/AOD/src/genLCSbase
+++ b/LCS/databases/AOD/src/genLCSbase
@@ -26,30 +26,17 @@
 # The generated files must be manually adjusted before they
 # can be used by genLCScode.
 #
-# $:Id $
+# $Id$
 #
-VERSION="v1.0"
+VERSION="v1.1"
 
 #---------------------------- Global routines ---------------------------------
 #
-# InitTmpfile
-#
-# Writes an informational header to the tempfile in case the file was not
-# removed by this script and to simplify debugging.
-#
-InitTmpfile()
-{
-	echo "#This temporarely file was generated by genDTL"
-	echo "#It should have been cleaned up by genDTL, please remove it"
-	echo "#ClassName:TableName:Ctype:MemberName:ColumnName:SubclassName:DBtype"
-}
-
-#
-# InitSrcfile
+# InitResultFile
 #
 # Adds an informational header to the result files
 #
-InitSrcfile()
+InitResultFile()
 {
 	echo -n "# This file was generated by genLCSbase ${VERSION} on " ; date
 	echo "# with the command: genLCSbase ${MODULE} <headerfiles>"
@@ -61,77 +48,181 @@ InitSrcfile()
 }
 
 #
-# StripComments filename
+# cleanlist filename
 #
-StripComments()
+# Removes all (partial) comment lines from the file
+#
+cleanlist()
 {
-	cat $1 | awk '{ 				# first remove all commentparts
-		CommentPos=index($0,"//")
-		if (CommentPos==0)
-			print $0
-		else
-			print substr($0,1,CommentPos-1)
-	}' | sed "s/^[ 	]//g" 			# strip leading spaces
+	cat $* |  \
+		# replace {} by ; , place { or } on new lines and force \n after ;
+		sed "s/{[ \t]*}/; /g ; s/[{}]/\n&\n/g ; s/;[ \t]/;\n/g" | \
+		# cut everthing after hashes
+		#		cut -d"#" -f1 | \
+		awk '{ if (NF > 0) print $0 }'
 }
 
 #
-# StripNameSpaces
+# analyseInfoFile file
 #
-# Leaves out the lines which belong to the namespace begin and end
+# Breaks down the info file (=precompiled headerfile) into the
+# functions, typedefs and variables.
+# The results are written to several temp files.
 #
-StripNameSpaces()
+analyseInfoFile()
 {
-	awk ' 	
-	BEGIN { 
-		BraceLevel=0		# Level of nested braces
-		NSStackSize=0		# Nr of namespaces on stack
-	}
-	{ 
-		# skip empty and comment lines
-		if ((length($0) == 0) || (substr($0,1,1) == "#")) {
-			next
-		}
-
-		# When a begin of a namespace is found add the current BraceLevel
-		# to the namespace stack.
-		while (index($0,"namespace") && (!index($0,"using"))) {
-			NameSpaceStack[NSStackSize++]=BraceLevel
-			while (index ($0, "{") == 0) {
-				getline
-			}
+	awk '
+	function skipTillNext(delimiter) {
+		while (match ($0, delimiter) == 0) {	# search delimiter
 			getline
 		}
+		$0=substr($0, RSTART+RLENGTH)
+		gsub("^[ 	]*", "")					# skip leading spaces
+	}
 
-		# determine nesting level 'after' this line
-		BraceLevel+=(split($0, dummy, "{")-1)
-		BraceLevel-=(split($0, dummy, "}")-1)
-
-		# when deeper nested than inner namespace, print the line
-		if (BraceLevel > NameSpaceStack[NSStackSize-1]) {
-			print $0
+	function getTillNext(delimiter,     result) {
+		result=""
+		while (match ($0, delimiter) == 0) {	# search delimiter
+			result = sprintf ("%s%s", result, $0)
+			getline
 		}
-		else {
-			# Level of inner namespace reached, pop namespace of stack
-			while (BraceLevel <= NameSpaceStack[NSStackSize-1]) {
-				BraceLevel++;
-				NSStackSize--;
+		result = sprintf ("%s%s", result, substr($0,1,RSTART+RLENGTH))
+		$0=substr($0, RSTART+RLENGTH)
+		gsub("^[ 	]*", "")					# skip leading spaces
+		gsub("[ \t][ \t]+", " ", result)		# skip double whitespace
+		return result
+	}
+
+	function handleTypedef(delimiter,    theTD) {
+		theTD=getTillNext(";");
+		if (index(theTD, "{") != 0) {
+			while (split(theTD, dummy, "{") > split(theTD, dummy, "}")) {
+				theTD=theTD getTillNext("}") getTillNext(";");
 			}
 		}
-	}'
+		gsub ("[ \t]+", " ", theTD)				# remove double spaces
+		print theTD >> "typedefs.LCS"
+	}
+
+	function handleFunction(delimiter,    theFunc) {
+		theFunct=getTillNext(";|{");
+		if (index(theFunct, "{") != 0) {
+			while (split(theFunct, dummy, "{") > split(theFunct, dummy, "}")) {
+				theFunct=theFunct getTillNext("}");
+			}
+		}
+		print theFunct >> "functions.LCS"
+	}
+
+	function pushOnStack(theType, theName) {
+		nameStack[stackSize]=theName
+		typeStack[stackSize]=theType
+		stackSize++
+	}
+
+	function pullFromStack(   topOfStack) {
+		stackSize--
+		topOfStack=typeStack[stackSize] nameStack[stackSize]
+		return topOfStack
+	}
+
+	BEGIN {
+		stackSize=1
+	}
+
+	/^[ 	]*/			{ gsub("^[ 	]*", "") }		# skip leading spaces
+	/[ 	]*$/			{ gsub("^[ 	]*", "") }		# skip trailing spaces
+	/^;/				{ next }					# remove loose ;
+	/^#/				{ File=$3 ; next }
+	/[ \t]*const[ \t]*/	{ gsub("[ \t]*const", "") }	# remove const
+	/\[.*[a-zA-Z]+.*]/	{ bpos=index($0,"[")
+						  epos=index($0,"]")
+						  $0=substr($0,1,bpos) "@@@" substr($0,epos)
+						}
+	/^using /			{ next }					# skip using commands
+	/^friend/			{ next }					# skip friend lines
+	/^public:/			{ Mode="publ" ; gsub("public:[ \t]*"   ,"") }
+	/^protected:/		{ Mode="prot" ; gsub("protected:[ \t]*","") }
+	/^private:/			{ Mode="priv" ; gsub("private:[ \t]*"  ,"") }
+	/^mutable/			{ gsub("mutable[ \t]*"  ,"") }
+	/^__extension__/	{ gsub("__extension__[ \t]*"  ,"") }
+	/^typedef/			{ handleTypedef(";|{") }
+	/^template/			{ skipTillNext(">") }
+	/^extern/			{ skipTillNext(";") }
+	/^enum/				{ skipTillNext("}") }
+	/^virtual/			{ handleFunction(";|{") }
+	/^inline/			{ handleFunction(";|{") }
+	/^[ \t]*\n/			{ next }
+	/^class|^struct/	{ if (index($0,";")) {		# forward declaration
+							next
+						  }
+						  else {
+							pushOnStack("C", Class)
+							Class=getTillNext("{")
+							gsub("[ \t]*{", "", Class)
+							gsub("^class ", "", Class)
+							nrMembers=0
+						  }
+						}
+	/^namespace/		{ pushOnStack("N", NameSpace)
+						  if (length(NameSpace) == 0) {
+							NameSpace=$2
+						  }
+						  else {
+							NameSpace=NameSpace "::" $2
+						  }
+						  skipTillNext("{")
+						}
+	/}/					{ prevName = pullFromStack() 
+						  if (substr(prevName,0,1) == "N") {
+							NameSpace=substr(prevName,2)
+						  }
+						  else {
+	  						if (nrMembers > 0) {
+							  # end the class definition with a marker
+							  # the contains the filename and the classname
+							  # note: the class MUST be on a non-existing place
+							  printf "%s@@@@@%s@\n", File , Class >"members.LCS"
+							}
+							Class=substr(prevName,2)
+						  }
+						  next
+						}
+
+	# Finally the non-conditional code
+	{ if (index($0,"(")) {
+		handleFunction(";|{")
+	  }
+	  if (length($0) == 0) {
+		next
+	  }
+	  printf "%s@%s@%s@%s@%s\n", File, NameSpace, Class, Mode, $0 >"members.LCS"
+	  nrMembers++
+	}
+	'
 }
 
 #
-# ConvertToMapfile filename
+# buildMapFile memberfile [class]
 #
-# Scans the header (and C++?) files to substract the class definitions
+# scan the just created memberfile and construct the mapfile
+# expanding the classes in the core-headerfile
 #
-ConvertToMapfile()
+buildMapFile()
 {
-	awk -v TMPFILE="$TMPFILE" ' 	
-	BEGIN { 
-		# By counting the '{' and '}' we know how deep we are nested. We are
-		# only interrested in level 1 information (declarations in a class).
-		NestedLevel=0
+	if [ "$2" == "" ]; then
+		# no class specification: everything in main headerfile
+		# first line of preprocessed file contains name of this file
+		grepmask=`tail -1 $1 | cut -d"@" -f1`
+		grepmask="^${grepmask}"
+	else
+		grepmask="@$2[ \t:publiclastru]*[a-zA-Z0-9_]*@"
+	fi
+	eval "grep '$grepmask' $1" | awk '
+
+	BEGIN {
+		prevClass="NoSuchClass"
+		prevBaseClass=""
 
 		# This table is used for transforming C types to Postgres types.
 		BasicType["short"]				= "SMALLINT"
@@ -152,88 +243,87 @@ ConvertToMapfile()
 		BasicType["uchar"]				= "VARCHAR"
 		BasicType["void"]				= "@@@???"
 	}
-	{ 
-		# skip empty and comment lines
-		if ((length($0) == 0) || (substr($0,1,1) == "#")) {
-			next
+
+	#
+	# resolveVariableType C-type
+	#
+	# Recursively tries to resolve the given C-type to a basictype
+	# known by Postgres.
+	#
+	function resolveVariableType(Ctype) {
+		if (Ctype in BasicType) {			# basic type?
+			return BasicType[Ctype]			# life is easy sometimes.
 		}
 
-		# determine nesting level 'after' this line
-		NestedLevel+=(split($0, dummy, "{")-1)
-		NestedLevel-=(split($0, dummy, "}")-1)
-
-		# When line contains "template<...>", cut it off
-		if (index($0,"template")) {
-			templateEnd=index($0, ">")+1
-			$0=substr($0,templateEnd)
+		VarType=resolveTypedef(Ctype)		# try resolving it as a typedef
+		if (substr(VarType,1,3) == "@@@") {	# unresolvable?
+			return VarType					# return failure
 		}
 
-		# begin of a class or struct?
-		if (index($0,"class") || index($0,"struct")) {
-			# assume a forward declaration when line ends in a semi-colon
-			if (index($0,";")) {
-				next
-			}
+		return resolveVariableType(VarType);	# resolve the result
+	}
 
-			# It looks like a real class
-			ClassName=$2
-			NestedBrackets=0
-			printf "\n"
-			printf "Class		%s\n",	ClassName
-			printf "Table		%s\n",	ClassName
-			printf "#\n"
-			printf "#TYPE              MEMBER             COLUMN             TYPE\n"
-			printf "#--------------------------------------------------------------------\n"
-			next
+	#
+	# resolveTypedef someType
+	#
+	# Searches the given variable_type in the typedefs-file created in
+	# the analyze-phase. When found it returns the original type.
+	# Otherwise @@@ is returned.
+	#
+	function resolveTypedef(varType,   theTypedef) {
+		# note: the get a result from a system command into awk we must
+		# pass it to a file and then read the file again.
+		Command=sprintf("grep %c %s;%c typedefs.LCS >tmp.LCS 2>/dev/null", 39, varType, 39);
+		system(Command)							# execute grep
+
+		theTypedef=""							# reset result
+		getline theTypedef <"tmp.LCS"			# get grep result
+		close("tmp.LCS")						# not needed anymore
+		if (length(theTypedef) <= 0) {			# not found?
+			return "@@@"						# return failure
 		}
 
-		# when outside any struct or class, just continue
-		if (NestedLevel != 1) {
-			next
-		}
+		gsub("^typedef ", "", theTypedef)		# cut off keyword typedef
+		gsub(" [a-zA-Z][^;]+;", "", theTypedef)	# cut off last word
+		gsub("{[^}]*}", "", theTypedef)			# cut struct definition
 
-		# skip several keywords
-		if (index($0,"public:") 	|| 
-			index($0,"protected:")	|| 
-			index($0,"private:")	||
-			index($0,"friend")) {
-			next
-		}
+		return theTypedef
+	}
 
-		# Function declaration may contain "(" and ")" on one line but
-		# the arguments may also be on several lines.
-
-		# determine bracket nesting 'after' this line
-		NestedBrackets+=(split($0, dummy, "(")-1)
-		NestedBrackets-=(split($0, dummy, ")")-1)
-
-		# Inside some brackets or brackets on this line? its a function
-		if (index($0,"(") || index($0,")") || (NestedBrackets>0)) {
-			next
-		}
-
-		# A brace on the line? ignore this line its prob. not a variable.
-		if (index($0,"{") || index($0,"}")) {
-			next
-		}
-
-		# Seems we have found a variable declaration
-		# Change the 'unsigned' word into 'u'xxxx
-		if ($1 == "unsigned") {
-			MemberType="u"$2
-			MemberName=$3
+	#
+	# resolveMemberInfo infotype definition_string
+	#
+	# A C(++) like variable declaration can be passed to this routine
+	# The routine analyzes and reformats the declaration and returns
+	# the required information (infotype)
+	# infotype: MT  Member Type
+	#			MN	Member Name
+	#			CT	Column Type (in database)
+	#			CN	Column Name (in database)
+	#
+	# Note: Since this routine makes up the database properties this is
+	# 		where the link between the C-code and the database is defined.
+	#
+	function resolveMemberInfo(infoType, argString) {
+		# infoType: MT / MN / CT / CN
+		gsub("[ \t][ \t]+", " ", argString)	# skip double spaces
+		split(argString, element, " ")
+		if (element[1] == "unsigned") {
+			# unsigned xxx --> uxxx
+			MemberType="u" element[2]
+			MemberName=element[3]
 			ArgNr=3
 		}
-		else {							# no keyword 'unsigned'
-			MemberType=$1
-			MemberName=$2
+		else {
+			MemberType=element[1]
+			MemberName=element[2]
 			ArgNr=2
 		}
 		if (MemberName == "long") {		# (unsigned) long long ?
 			MemberType=MemberType MemberName
-			MemberName=$(++ArgNr)
+			MemberName=element[++ArgNr]
 		}
-
+		
 		# When the member is a pointer or a reference append
 		# a * to the MemberType and remove to original & or *
 		# NOTE: it is trivial whether is was a * or a & we dont
@@ -242,10 +332,10 @@ ConvertToMapfile()
 		# * or & attached to membername? move it to membertype
 		if ((MemberName == "&") || (MemberName == "*")) {
 			MemberType=MemberType"*"
-			MemberName=$(++ArgNr)
+			MemberName=element[++ArgNr]
 		}
-		gsub("&","*",MemberType)		# treat & as *
-		gsub(";","",MemberName)			# strip off line termination
+		gsub("&","*",MemberType)				# treat & as *
+		gsub("[ \t]*;","",MemberName)			# strip off line termination
 
 		# move pointer and references to the MemberType
 		if (index(MemberName,"*") || index(MemberName,"&")) {
@@ -253,6 +343,13 @@ ConvertToMapfile()
 			gsub("&","",MemberName)
 			MemberType=MemberType"*"
 		}
+		PlainMemberType=MemberType
+		gsub("*","",PlainMemberType)		# MemberType without '*'
+
+		if (infoType == "MN") { return MemberName }
+		if (infoType == "MT") { return MemberType }
+
+		# Convert the member-characteristics to database characteristics.
 
 		# When the variable is an array, find out its length
 		ArrSize=1
@@ -267,24 +364,75 @@ ConvertToMapfile()
 		}
 
 		# Construct the database equivalents
-		PlainMemberType=MemberType
-		gsub("*","",PlainMemberType)		# MemberType without '*'
-		if (PlainMemberType in BasicType) {
-			ColumnType=BasicType[PlainMemberType]
+		ColumnType=resolveVariableType(PlainMemberType)
+		if (substr(ColumnType,1,3) != "@@@") {			# familiar type?
 			ColumnName=toupper(MemberName)
 			if (ColumnType == "VARCHAR") {
 				ColumnType=ColumnType "(" ArrSize ")"
 			}
 		}
-		else {
+		else {											# unknown type
 			ColumnType="@@@"PlainMemberType
 			ColumnName="Class"
 		}
+		if (infoType == "CN") 
+			return ColumnName
+		else
+			return ColumnType
+	}
+
+	function addBaseClass(baseClass) {
+		if (length(baseClass) <= 0) {
+			return;
+		}
+		MemberName="BC" baseClass
+		ColumnName="BaseClass"
+		printf "%-18s %-18s %-18s %s\n", baseClass, MemberName, ColumnName, baseClass
+	}
+
+	# MAIN awk loop
+	{ 
+		split($0, field, "@")
+		Class=field[3]
+		BaseClass=""
+		if (index(Class,":")>0) {				# is class derived from other?
+			gsub("[ \t]*:[ \t]*public", "", Class)
+			split(Class, part, " ")
+			Class=part[1]
+			BaseClass=part[2]
+		}
+
+		if (Class != prevClass) {				# start of a new class?
+			addBaseClass(prevBaseClass);		# class last class
+
+			if (Class == "") {				# EndOfClass marker?
+				next
+			}
+
+			printf "\n"
+			printf "Class		%s\n", Class
+			printf "Table		%s\n", Class
+			printf "#TYPE              MEMBER             COLUMN             TYPE\n"
+			printf "#--------------------------------------------------------------------\n"
+			prevClass=Class
+			prevBaseClass=BaseClass
+
+			print Class >>"mapped.LCS"
+			if (BaseClass != "") {
+				print BaseClass >>"needed.LCS"
+			}
+		}
+
+		MemberType=resolveMemberInfo("MT", field[5])
+		MemberName=resolveMemberInfo("MN", field[5])
+		ColumnType=resolveMemberInfo("CT", field[5])
+		ColumnName=resolveMemberInfo("CN", field[5])
 
 		printf "%-18s %-18s %-18s %s\n", MemberType, MemberName, ColumnName, ColumnType
-
-		printf "%s\n", ClassName >>TMPFILE
-	}'
+		if (ColumnName == "Class" || ColumnName == "BaseClass") {
+			print substr(ColumnType,4) >>"needed.LCS"
+		}
+	} '
 }
 
 #
@@ -300,12 +448,12 @@ ConstructFunfile()
 	}'
 }
 
-#------------------------------- MAIN program ---------------------------------
+#------------------------------- MAIN ----------------------------------------
 #
 # Check invocation syntax: genLCSbase module headerfiles
 #
 case $# in
-	0)	echo "Syntax: $0 module headerfiles"
+	0|1)	echo "Syntax: $0 module headerfiles"
 		exit 0
 		;;
 	*)	MODULE=$1
@@ -316,22 +464,58 @@ esac
 
 # Initialize some variables
 #
-TMPFILE=map.genLCSbase.$$
 MAPFILE=${MODULE}.map.proto
 FUNFILE=${MODULE}.fun.proto
 
 # Write headers to the result files.
-InitTmpfile		> ${TMPFILE}
-InitSrcfile  	> ${MAPFILE}
-InitSrcfile  	> ${FUNFILE}
+InitResultFile  	> ${MAPFILE}
+InitResultFile  	> ${FUNFILE}
 
 # Scan the headerfiles and substract the class hierarchy
 for file in ${HEADERFILES}
 do
-	StripComments $file | StripNameSpaces | ConvertToMapfile >>${MAPFILE}
+	rm -f typedefs.LCS functions.LCS members.LCS \
+		  needed.LCS mapped.LCS missing.LCS
+
+	# First stage: break down precompiled headerfile into:
+	#		typedefs.LCS
+	#		functions.LCS
+	#		members.LCS
+	cleanlist $file | analyseInfoFile
+
+	# Second stage: Construct mapfile from all classes in main headerfile
+	buildMapFile members.LCS >>${MAPFILE}
+
+	# Third stage (repeating): Add the base- and embedded- classes
+	complete=false
+	while (! $complete)
+	do
+		if [ ! -f "needed.LCS" ]; then
+			complete=true
+			break
+		fi
+
+		sort needed.LCS | uniq >adding.LCS
+		rm -f needed.LCS
+		cat adding.LCS | while read classname
+		do
+			grep $classname mapped.LCS >/dev/null 2>&1
+			if [ $? -ne 0 ]; then		# not found?
+				buildMapFile members.LCS $classname >>${MAPFILE}
+				grep $classname mapped.LCS >/dev/null 2>&1
+				if [ $? -ne 0 ]; then		# still not found?
+					echo $classname >>missing.LCS
+				fi
+			fi
+		done
+		rm adding.LCS
+	done
+
+	ConstructFunfile mapped.LCS >>${FUNFILE}
 done
 
-# TMPFILE contains the used classes now
-ConstructFunfile ${TMPFILE} >>${FUNFILE}
-	
-rm -f ${TMPFILE}
+if [ -f missing.LCS ]; then
+	echo "WARNING: The following types or classes could not be resolved:"
+	cat missing.LCS
+fi
+
